/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.api;

import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.*;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.auth.*;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.Community;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.GetAllCommunitiesResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommunitiesApi
 */
public class CommunitiesApiTest {

    private final CommunitiesApi api = new CommunitiesApi();

    /**
     * Getting all communities
     *
     * This method renders communities ordered by creation date (ascending).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllCommunitiesTest() throws ApiException {
        //Integer offset = null;
        //Integer limit = null;
        //GetAllCommunitiesResponse response = api.getAllCommunities(offset, limit);
        // TODO: test validations
    }

    /**
     * Getting a community from its id
     *
     * This method renders a community from given id.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCommunityTest() throws ApiException {
        //String communityId = null;
        //Community response = api.getCommunity(communityId);
        // TODO: test validations
    }

}
