/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.api;

import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.*;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.auth.*;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.Settings;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SettingsApi
 */
public class SettingsApiTest {

    private final SettingsApi api = new SettingsApi();

    /**
     * Getting all settings
     *
     * This method renders all settings of your domain.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllSettingsTest() throws ApiException {
        //Settings response = api.getAllSettings();
        // TODO: test validations
    }

    /**
     * Updating settings
     *
     * This method updates the current domain settings.  Authorization​: only users that can update settings.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSettingsTest() throws ApiException {
        //Integer activityPresenceThreshold = null;
        //Boolean activityTracking = null;
        //String beginningOfWeek = null;
        //Boolean categoryTagging = null;
        //String contentLanguages = null;
        //Boolean dashboard = null;
        //Boolean denyIframeIntegration = null;
        //Boolean disablePasswordAutocomplete = null;
        //Integer expirePasswordAfter = null;
        //Boolean enableAutoScrollDown = null;
        //Boolean expirePasswordEnabled = null;
        //Boolean exportInSeconds = null;
        //Boolean foldUselessContents = null;
        //Integer fteDuration = null;
        //Boolean identityMerge = null;
        //List<Integer> interventionDeferRates = null;
        //Integer interventionDeferThreshold = null;
        //List<Integer> interventionRates = null;
        //String locale = null;
        //Boolean multiLang = null;
        //String name = null;
        //Boolean passwordArchivableEnabled = null;
        //Integer passwordArchivableSize = null;
        //Integer passwordMinLength = null;
        //Boolean passwordNonWord = null;
        //Boolean passwordNumbers = null;
        //Boolean passwordRecoveryDisabled = null;
        //Boolean pushEnabled = null;
        //Boolean replyAsAnyIdentity = null;
        //Boolean rtlSupport = null;
        //Boolean selfApprovalRequired = null;
        //Integer sessionTimeout = null;
        //Boolean spellchecking = null;
        //String style = null;
        //Boolean thirdPartyServicesDisabled = null;
        //String timezone = null;
        //Boolean trackJs = null;
        //String type = null;
        //Integer urgentTaskThreshold = null;
        //Boolean useSystemFont = null;
        //Settings response = api.updateSettings(activityPresenceThreshold, activityTracking, beginningOfWeek, categoryTagging, contentLanguages, dashboard, denyIframeIntegration, disablePasswordAutocomplete, expirePasswordAfter, enableAutoScrollDown, expirePasswordEnabled, exportInSeconds, foldUselessContents, fteDuration, identityMerge, interventionDeferRates, interventionDeferThreshold, interventionRates, locale, multiLang, name, passwordArchivableEnabled, passwordArchivableSize, passwordMinLength, passwordNonWord, passwordNumbers, passwordRecoveryDisabled, pushEnabled, replyAsAnyIdentity, rtlSupport, selfApprovalRequired, sessionTimeout, spellchecking, style, thirdPartyServicesDisabled, timezone, trackJs, type, urgentTaskThreshold, useSystemFont);
        // TODO: test validations
    }

}
