/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.api;

import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.*;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.auth.*;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.SurveyResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SurveyResponsesApi
 */
public class SurveyResponsesApiTest {

    private final SurveyResponsesApi api = new SurveyResponsesApi();

    /**
     * Get a survey response
     *
     * This method returns information about a survey response.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSurveyResponseTest() throws ApiException {
        //String surveyResponseId = null;
        //SurveyResponse response = api.getSurveyResponse(surveyResponseId);
        // TODO: test validations
    }

}
