/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.JSON;


/**
 * Role
 */
@JsonPropertyOrder({
  Role.JSON_PROPERTY_ACCESS_HELP_CENTER,
  Role.JSON_PROPERTY_ACCESS_PREVIOUS_MESSAGES,
  Role.JSON_PROPERTY_ACCESS_PULL_MODE,
  Role.JSON_PROPERTY_ADMIN_STAMP_ANSWER,
  Role.JSON_PROPERTY_ANONYMIZE_IDENTITY,
  Role.JSON_PROPERTY_APPROVE_CONTENT,
  Role.JSON_PROPERTY_ASK_AN_EXPERT,
  Role.JSON_PROPERTY_ASSIGN_INTERVENTION,
  Role.JSON_PROPERTY_AUTHOR_BLOCK_CONTENT,
  Role.JSON_PROPERTY_CLOSE_CONTENT_THREAD,
  Role.JSON_PROPERTY_CREATE_AND_DESTROY_EXTENSION,
  Role.JSON_PROPERTY_CREATE_COMMUNITY,
  Role.JSON_PROPERTY_CREATE_CONTENT_SOURCE,
  Role.JSON_PROPERTY_CREATE_USER,
  Role.JSON_PROPERTY_CREATED_AT,
  Role.JSON_PROPERTY_DELAY_EXPORT_CONTENT,
  Role.JSON_PROPERTY_DELETE_CONTENT_THREAD,
  Role.JSON_PROPERTY_ESCALATE_TO_VIDEO,
  Role.JSON_PROPERTY_EXPORT_IDENTITY,
  Role.JSON_PROPERTY_ID,
  Role.JSON_PROPERTY_IMPERSONATE_USER,
  Role.JSON_PROPERTY_INVITE_USER,
  Role.JSON_PROPERTY_LABEL,
  Role.JSON_PROPERTY_LOCK_IDENTITY,
  Role.JSON_PROPERTY_MANAGE_API_ACCESS_TOKENS,
  Role.JSON_PROPERTY_MANAGE_APP_SDK_APPLICATIONS,
  Role.JSON_PROPERTY_MANAGE_CATEGORIES,
  Role.JSON_PROPERTY_MANAGE_CHAT,
  Role.JSON_PROPERTY_MANAGE_CUSTOM_FIELDS,
  Role.JSON_PROPERTY_MANAGE_CUSTOM_NOTIFICATIONS,
  Role.JSON_PROPERTY_MANAGE_EMAILS_TEMPLATES,
  Role.JSON_PROPERTY_MANAGE_FOLDERS,
  Role.JSON_PROPERTY_MANAGE_ICE,
  Role.JSON_PROPERTY_MANAGE_IDENTITIES,
  Role.JSON_PROPERTY_MANAGE_MESSAGING,
  Role.JSON_PROPERTY_MANAGE_OWN_NOTIFICATIONS,
  Role.JSON_PROPERTY_MANAGE_REPLY_ASSISTANT,
  Role.JSON_PROPERTY_MANAGE_ROLES,
  Role.JSON_PROPERTY_MANAGE_RULES_ENGINE_RULES,
  Role.JSON_PROPERTY_MANAGE_TAGS,
  Role.JSON_PROPERTY_MANAGE_TEAMS,
  Role.JSON_PROPERTY_MANAGE_TOPOLOGIES,
  Role.JSON_PROPERTY_MANAGE_USERS_OF_MY_TEAMS,
  Role.JSON_PROPERTY_MONITOR_TASKS,
  Role.JSON_PROPERTY_MONITOR_TEAM_TASKS,
  Role.JSON_PROPERTY_MUTE_CONTENT,
  Role.JSON_PROPERTY_OPEN_CONTENT_THREAD,
  Role.JSON_PROPERTY_PUBLISH_CONTENT,
  Role.JSON_PROPERTY_READ_COMMUNITY,
  Role.JSON_PROPERTY_READ_CONTENT_SOURCE,
  Role.JSON_PROPERTY_READ_EVENT,
  Role.JSON_PROPERTY_READ_EXPORT,
  Role.JSON_PROPERTY_READ_IDENTITY,
  Role.JSON_PROPERTY_READ_OWN_STATS,
  Role.JSON_PROPERTY_READ_PRESENCE,
  Role.JSON_PROPERTY_READ_STATS,
  Role.JSON_PROPERTY_READ_USER,
  Role.JSON_PROPERTY_RECEIVE_TASKS,
  Role.JSON_PROPERTY_REPLY_WITH_ASSISTANT,
  Role.JSON_PROPERTY_SEARCH_CONTENTS,
  Role.JSON_PROPERTY_SEARCH_EVENT,
  Role.JSON_PROPERTY_UPDATE_COMMUNITY,
  Role.JSON_PROPERTY_UPDATE_CONTENT_SOURCE,
  Role.JSON_PROPERTY_UPDATE_EXTENSION,
  Role.JSON_PROPERTY_UPDATE_IDENTITY,
  Role.JSON_PROPERTY_UPDATE_INTERVENTION,
  Role.JSON_PROPERTY_UPDATE_OWN_INTERVENTION,
  Role.JSON_PROPERTY_UPDATE_SETTINGS,
  Role.JSON_PROPERTY_UPDATE_TIME_SHEET,
  Role.JSON_PROPERTY_UPDATE_USER,
  Role.JSON_PROPERTY_UPDATED_AT,
  Role.JSON_PROPERTY_USE_COBROWSING,
  Role.JSON_PROPERTY_USE_EMOJI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-03-13T22:37:55.741968+01:00[Europe/Paris]")
public class Role implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ACCESS_HELP_CENTER = "access_help_center";
  private Boolean accessHelpCenter;

  public static final String JSON_PROPERTY_ACCESS_PREVIOUS_MESSAGES = "access_previous_messages";
  private Boolean accessPreviousMessages;

  public static final String JSON_PROPERTY_ACCESS_PULL_MODE = "access_pull_mode";
  private Boolean accessPullMode;

  public static final String JSON_PROPERTY_ADMIN_STAMP_ANSWER = "admin_stamp_answer";
  private Boolean adminStampAnswer;

  public static final String JSON_PROPERTY_ANONYMIZE_IDENTITY = "anonymize_identity";
  private Boolean anonymizeIdentity;

  public static final String JSON_PROPERTY_APPROVE_CONTENT = "approve_content";
  private Boolean approveContent;

  public static final String JSON_PROPERTY_ASK_AN_EXPERT = "ask_an_expert";
  private Boolean askAnExpert;

  public static final String JSON_PROPERTY_ASSIGN_INTERVENTION = "assign_intervention";
  private Boolean assignIntervention;

  public static final String JSON_PROPERTY_AUTHOR_BLOCK_CONTENT = "author_block_content";
  private Boolean authorBlockContent;

  public static final String JSON_PROPERTY_CLOSE_CONTENT_THREAD = "close_content_thread";
  private Boolean closeContentThread;

  public static final String JSON_PROPERTY_CREATE_AND_DESTROY_EXTENSION = "create_and_destroy_extension";
  private Boolean createAndDestroyExtension;

  public static final String JSON_PROPERTY_CREATE_COMMUNITY = "create_community";
  private Boolean createCommunity;

  public static final String JSON_PROPERTY_CREATE_CONTENT_SOURCE = "create_content_source";
  private Boolean createContentSource;

  public static final String JSON_PROPERTY_CREATE_USER = "create_user";
  private Boolean createUser;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_DELAY_EXPORT_CONTENT = "delay_export_content";
  private Boolean delayExportContent;

  public static final String JSON_PROPERTY_DELETE_CONTENT_THREAD = "delete_content_thread";
  private Boolean deleteContentThread;

  public static final String JSON_PROPERTY_ESCALATE_TO_VIDEO = "escalate_to_video";
  private Boolean escalateToVideo;

  public static final String JSON_PROPERTY_EXPORT_IDENTITY = "export_identity";
  private Boolean exportIdentity;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_IMPERSONATE_USER = "impersonate_user";
  private Boolean impersonateUser;

  public static final String JSON_PROPERTY_INVITE_USER = "invite_user";
  private Boolean inviteUser;

  public static final String JSON_PROPERTY_LABEL = "label";
  private String label;

  public static final String JSON_PROPERTY_LOCK_IDENTITY = "lock_identity";
  private Boolean lockIdentity;

  public static final String JSON_PROPERTY_MANAGE_API_ACCESS_TOKENS = "manage_api_access_tokens";
  private Boolean manageApiAccessTokens;

  public static final String JSON_PROPERTY_MANAGE_APP_SDK_APPLICATIONS = "manage_app_sdk_applications";
  private Boolean manageAppSdkApplications;

  public static final String JSON_PROPERTY_MANAGE_CATEGORIES = "manage_categories";
  private Boolean manageCategories;

  public static final String JSON_PROPERTY_MANAGE_CHAT = "manage_chat";
  private Boolean manageChat;

  public static final String JSON_PROPERTY_MANAGE_CUSTOM_FIELDS = "manage_custom_fields";
  private Boolean manageCustomFields;

  public static final String JSON_PROPERTY_MANAGE_CUSTOM_NOTIFICATIONS = "manage_custom_notifications";
  private Boolean manageCustomNotifications;

  public static final String JSON_PROPERTY_MANAGE_EMAILS_TEMPLATES = "manage_emails_templates";
  private Boolean manageEmailsTemplates;

  public static final String JSON_PROPERTY_MANAGE_FOLDERS = "manage_folders";
  private Boolean manageFolders;

  public static final String JSON_PROPERTY_MANAGE_ICE = "manage_ice";
  private Boolean manageIce;

  public static final String JSON_PROPERTY_MANAGE_IDENTITIES = "manage_identities";
  private Boolean manageIdentities;

  public static final String JSON_PROPERTY_MANAGE_MESSAGING = "manage_messaging";
  private Boolean manageMessaging;

  public static final String JSON_PROPERTY_MANAGE_OWN_NOTIFICATIONS = "manage_own_notifications";
  private Boolean manageOwnNotifications;

  public static final String JSON_PROPERTY_MANAGE_REPLY_ASSISTANT = "manage_reply_assistant";
  private Boolean manageReplyAssistant;

  public static final String JSON_PROPERTY_MANAGE_ROLES = "manage_roles";
  private Boolean manageRoles;

  public static final String JSON_PROPERTY_MANAGE_RULES_ENGINE_RULES = "manage_rules_engine_rules";
  private Boolean manageRulesEngineRules;

  public static final String JSON_PROPERTY_MANAGE_TAGS = "manage_tags";
  private Boolean manageTags;

  public static final String JSON_PROPERTY_MANAGE_TEAMS = "manage_teams";
  private Boolean manageTeams;

  public static final String JSON_PROPERTY_MANAGE_TOPOLOGIES = "manage_topologies";
  private Boolean manageTopologies;

  public static final String JSON_PROPERTY_MANAGE_USERS_OF_MY_TEAMS = "manage_users_of_my_teams";
  private Boolean manageUsersOfMyTeams;

  public static final String JSON_PROPERTY_MONITOR_TASKS = "monitor_tasks";
  private Boolean monitorTasks;

  public static final String JSON_PROPERTY_MONITOR_TEAM_TASKS = "monitor_team_tasks";
  private Boolean monitorTeamTasks;

  public static final String JSON_PROPERTY_MUTE_CONTENT = "mute_content";
  private Boolean muteContent;

  public static final String JSON_PROPERTY_OPEN_CONTENT_THREAD = "open_content_thread";
  private Boolean openContentThread;

  public static final String JSON_PROPERTY_PUBLISH_CONTENT = "publish_content";
  private Boolean publishContent;

  public static final String JSON_PROPERTY_READ_COMMUNITY = "read_community";
  private Boolean readCommunity;

  public static final String JSON_PROPERTY_READ_CONTENT_SOURCE = "read_content_source";
  private Boolean readContentSource;

  public static final String JSON_PROPERTY_READ_EVENT = "read_event";
  private Boolean readEvent;

  public static final String JSON_PROPERTY_READ_EXPORT = "read_export";
  private Boolean readExport;

  public static final String JSON_PROPERTY_READ_IDENTITY = "read_identity";
  private Boolean readIdentity;

  public static final String JSON_PROPERTY_READ_OWN_STATS = "read_own_stats";
  private Boolean readOwnStats;

  public static final String JSON_PROPERTY_READ_PRESENCE = "read_presence";
  private Boolean readPresence;

  public static final String JSON_PROPERTY_READ_STATS = "read_stats";
  private Boolean readStats;

  public static final String JSON_PROPERTY_READ_USER = "read_user";
  private Boolean readUser;

  public static final String JSON_PROPERTY_RECEIVE_TASKS = "receive_tasks";
  private Boolean receiveTasks;

  public static final String JSON_PROPERTY_REPLY_WITH_ASSISTANT = "reply_with_assistant";
  private Boolean replyWithAssistant;

  public static final String JSON_PROPERTY_SEARCH_CONTENTS = "search_contents";
  private Boolean searchContents;

  public static final String JSON_PROPERTY_SEARCH_EVENT = "search_event";
  private Boolean searchEvent;

  public static final String JSON_PROPERTY_UPDATE_COMMUNITY = "update_community";
  private Boolean updateCommunity;

  public static final String JSON_PROPERTY_UPDATE_CONTENT_SOURCE = "update_content_source";
  private Boolean updateContentSource;

  public static final String JSON_PROPERTY_UPDATE_EXTENSION = "update_extension";
  private Boolean updateExtension;

  public static final String JSON_PROPERTY_UPDATE_IDENTITY = "update_identity";
  private Boolean updateIdentity;

  public static final String JSON_PROPERTY_UPDATE_INTERVENTION = "update_intervention";
  private Boolean updateIntervention;

  public static final String JSON_PROPERTY_UPDATE_OWN_INTERVENTION = "update_own_intervention";
  private Boolean updateOwnIntervention;

  public static final String JSON_PROPERTY_UPDATE_SETTINGS = "update_settings";
  private Boolean updateSettings;

  public static final String JSON_PROPERTY_UPDATE_TIME_SHEET = "update_time_sheet";
  private Boolean updateTimeSheet;

  public static final String JSON_PROPERTY_UPDATE_USER = "update_user";
  private Boolean updateUser;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_USE_COBROWSING = "use_cobrowsing";
  private Boolean useCobrowsing;

  public static final String JSON_PROPERTY_USE_EMOJI = "use_emoji";
  private Boolean useEmoji;

  public Role() { 
  }

  public Role accessHelpCenter(Boolean accessHelpCenter) {
    this.accessHelpCenter = accessHelpCenter;
    return this;
  }

   /**
   * Get accessHelpCenter
   * @return accessHelpCenter
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_HELP_CENTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAccessHelpCenter() {
    return accessHelpCenter;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_HELP_CENTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessHelpCenter(Boolean accessHelpCenter) {
    this.accessHelpCenter = accessHelpCenter;
  }


  public Role accessPreviousMessages(Boolean accessPreviousMessages) {
    this.accessPreviousMessages = accessPreviousMessages;
    return this;
  }

   /**
   * Get accessPreviousMessages
   * @return accessPreviousMessages
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_PREVIOUS_MESSAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAccessPreviousMessages() {
    return accessPreviousMessages;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_PREVIOUS_MESSAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessPreviousMessages(Boolean accessPreviousMessages) {
    this.accessPreviousMessages = accessPreviousMessages;
  }


  public Role accessPullMode(Boolean accessPullMode) {
    this.accessPullMode = accessPullMode;
    return this;
  }

   /**
   * Get accessPullMode
   * @return accessPullMode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_PULL_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAccessPullMode() {
    return accessPullMode;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_PULL_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessPullMode(Boolean accessPullMode) {
    this.accessPullMode = accessPullMode;
  }


  public Role adminStampAnswer(Boolean adminStampAnswer) {
    this.adminStampAnswer = adminStampAnswer;
    return this;
  }

   /**
   * Get adminStampAnswer
   * @return adminStampAnswer
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADMIN_STAMP_ANSWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAdminStampAnswer() {
    return adminStampAnswer;
  }


  @JsonProperty(JSON_PROPERTY_ADMIN_STAMP_ANSWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdminStampAnswer(Boolean adminStampAnswer) {
    this.adminStampAnswer = adminStampAnswer;
  }


  public Role anonymizeIdentity(Boolean anonymizeIdentity) {
    this.anonymizeIdentity = anonymizeIdentity;
    return this;
  }

   /**
   * Get anonymizeIdentity
   * @return anonymizeIdentity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANONYMIZE_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAnonymizeIdentity() {
    return anonymizeIdentity;
  }


  @JsonProperty(JSON_PROPERTY_ANONYMIZE_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnonymizeIdentity(Boolean anonymizeIdentity) {
    this.anonymizeIdentity = anonymizeIdentity;
  }


  public Role approveContent(Boolean approveContent) {
    this.approveContent = approveContent;
    return this;
  }

   /**
   * Get approveContent
   * @return approveContent
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPROVE_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getApproveContent() {
    return approveContent;
  }


  @JsonProperty(JSON_PROPERTY_APPROVE_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApproveContent(Boolean approveContent) {
    this.approveContent = approveContent;
  }


  public Role askAnExpert(Boolean askAnExpert) {
    this.askAnExpert = askAnExpert;
    return this;
  }

   /**
   * Get askAnExpert
   * @return askAnExpert
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASK_AN_EXPERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAskAnExpert() {
    return askAnExpert;
  }


  @JsonProperty(JSON_PROPERTY_ASK_AN_EXPERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAskAnExpert(Boolean askAnExpert) {
    this.askAnExpert = askAnExpert;
  }


  public Role assignIntervention(Boolean assignIntervention) {
    this.assignIntervention = assignIntervention;
    return this;
  }

   /**
   * Get assignIntervention
   * @return assignIntervention
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSIGN_INTERVENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAssignIntervention() {
    return assignIntervention;
  }


  @JsonProperty(JSON_PROPERTY_ASSIGN_INTERVENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssignIntervention(Boolean assignIntervention) {
    this.assignIntervention = assignIntervention;
  }


  public Role authorBlockContent(Boolean authorBlockContent) {
    this.authorBlockContent = authorBlockContent;
    return this;
  }

   /**
   * Get authorBlockContent
   * @return authorBlockContent
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHOR_BLOCK_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAuthorBlockContent() {
    return authorBlockContent;
  }


  @JsonProperty(JSON_PROPERTY_AUTHOR_BLOCK_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthorBlockContent(Boolean authorBlockContent) {
    this.authorBlockContent = authorBlockContent;
  }


  public Role closeContentThread(Boolean closeContentThread) {
    this.closeContentThread = closeContentThread;
    return this;
  }

   /**
   * Get closeContentThread
   * @return closeContentThread
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLOSE_CONTENT_THREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCloseContentThread() {
    return closeContentThread;
  }


  @JsonProperty(JSON_PROPERTY_CLOSE_CONTENT_THREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCloseContentThread(Boolean closeContentThread) {
    this.closeContentThread = closeContentThread;
  }


  public Role createAndDestroyExtension(Boolean createAndDestroyExtension) {
    this.createAndDestroyExtension = createAndDestroyExtension;
    return this;
  }

   /**
   * Get createAndDestroyExtension
   * @return createAndDestroyExtension
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_AND_DESTROY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCreateAndDestroyExtension() {
    return createAndDestroyExtension;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_AND_DESTROY_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateAndDestroyExtension(Boolean createAndDestroyExtension) {
    this.createAndDestroyExtension = createAndDestroyExtension;
  }


  public Role createCommunity(Boolean createCommunity) {
    this.createCommunity = createCommunity;
    return this;
  }

   /**
   * Get createCommunity
   * @return createCommunity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_COMMUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCreateCommunity() {
    return createCommunity;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_COMMUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateCommunity(Boolean createCommunity) {
    this.createCommunity = createCommunity;
  }


  public Role createContentSource(Boolean createContentSource) {
    this.createContentSource = createContentSource;
    return this;
  }

   /**
   * Get createContentSource
   * @return createContentSource
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_CONTENT_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCreateContentSource() {
    return createContentSource;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_CONTENT_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateContentSource(Boolean createContentSource) {
    this.createContentSource = createContentSource;
  }


  public Role createUser(Boolean createUser) {
    this.createUser = createUser;
    return this;
  }

   /**
   * Get createUser
   * @return createUser
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCreateUser() {
    return createUser;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateUser(Boolean createUser) {
    this.createUser = createUser;
  }


  public Role createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Role delayExportContent(Boolean delayExportContent) {
    this.delayExportContent = delayExportContent;
    return this;
  }

   /**
   * Get delayExportContent
   * @return delayExportContent
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELAY_EXPORT_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDelayExportContent() {
    return delayExportContent;
  }


  @JsonProperty(JSON_PROPERTY_DELAY_EXPORT_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDelayExportContent(Boolean delayExportContent) {
    this.delayExportContent = delayExportContent;
  }


  public Role deleteContentThread(Boolean deleteContentThread) {
    this.deleteContentThread = deleteContentThread;
    return this;
  }

   /**
   * Get deleteContentThread
   * @return deleteContentThread
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETE_CONTENT_THREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleteContentThread() {
    return deleteContentThread;
  }


  @JsonProperty(JSON_PROPERTY_DELETE_CONTENT_THREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleteContentThread(Boolean deleteContentThread) {
    this.deleteContentThread = deleteContentThread;
  }


  public Role escalateToVideo(Boolean escalateToVideo) {
    this.escalateToVideo = escalateToVideo;
    return this;
  }

   /**
   * Get escalateToVideo
   * @return escalateToVideo
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESCALATE_TO_VIDEO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEscalateToVideo() {
    return escalateToVideo;
  }


  @JsonProperty(JSON_PROPERTY_ESCALATE_TO_VIDEO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEscalateToVideo(Boolean escalateToVideo) {
    this.escalateToVideo = escalateToVideo;
  }


  public Role exportIdentity(Boolean exportIdentity) {
    this.exportIdentity = exportIdentity;
    return this;
  }

   /**
   * Get exportIdentity
   * @return exportIdentity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPORT_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getExportIdentity() {
    return exportIdentity;
  }


  @JsonProperty(JSON_PROPERTY_EXPORT_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExportIdentity(Boolean exportIdentity) {
    this.exportIdentity = exportIdentity;
  }


  public Role id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public Role impersonateUser(Boolean impersonateUser) {
    this.impersonateUser = impersonateUser;
    return this;
  }

   /**
   * Get impersonateUser
   * @return impersonateUser
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMPERSONATE_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getImpersonateUser() {
    return impersonateUser;
  }


  @JsonProperty(JSON_PROPERTY_IMPERSONATE_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImpersonateUser(Boolean impersonateUser) {
    this.impersonateUser = impersonateUser;
  }


  public Role inviteUser(Boolean inviteUser) {
    this.inviteUser = inviteUser;
    return this;
  }

   /**
   * Get inviteUser
   * @return inviteUser
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVITE_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInviteUser() {
    return inviteUser;
  }


  @JsonProperty(JSON_PROPERTY_INVITE_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInviteUser(Boolean inviteUser) {
    this.inviteUser = inviteUser;
  }


  public Role label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLabel() {
    return label;
  }


  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabel(String label) {
    this.label = label;
  }


  public Role lockIdentity(Boolean lockIdentity) {
    this.lockIdentity = lockIdentity;
    return this;
  }

   /**
   * Get lockIdentity
   * @return lockIdentity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCK_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLockIdentity() {
    return lockIdentity;
  }


  @JsonProperty(JSON_PROPERTY_LOCK_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockIdentity(Boolean lockIdentity) {
    this.lockIdentity = lockIdentity;
  }


  public Role manageApiAccessTokens(Boolean manageApiAccessTokens) {
    this.manageApiAccessTokens = manageApiAccessTokens;
    return this;
  }

   /**
   * Get manageApiAccessTokens
   * @return manageApiAccessTokens
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_API_ACCESS_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageApiAccessTokens() {
    return manageApiAccessTokens;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_API_ACCESS_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageApiAccessTokens(Boolean manageApiAccessTokens) {
    this.manageApiAccessTokens = manageApiAccessTokens;
  }


  public Role manageAppSdkApplications(Boolean manageAppSdkApplications) {
    this.manageAppSdkApplications = manageAppSdkApplications;
    return this;
  }

   /**
   * Get manageAppSdkApplications
   * @return manageAppSdkApplications
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_APP_SDK_APPLICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageAppSdkApplications() {
    return manageAppSdkApplications;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_APP_SDK_APPLICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageAppSdkApplications(Boolean manageAppSdkApplications) {
    this.manageAppSdkApplications = manageAppSdkApplications;
  }


  public Role manageCategories(Boolean manageCategories) {
    this.manageCategories = manageCategories;
    return this;
  }

   /**
   * Get manageCategories
   * @return manageCategories
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageCategories() {
    return manageCategories;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageCategories(Boolean manageCategories) {
    this.manageCategories = manageCategories;
  }


  public Role manageChat(Boolean manageChat) {
    this.manageChat = manageChat;
    return this;
  }

   /**
   * Get manageChat
   * @return manageChat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageChat() {
    return manageChat;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageChat(Boolean manageChat) {
    this.manageChat = manageChat;
  }


  public Role manageCustomFields(Boolean manageCustomFields) {
    this.manageCustomFields = manageCustomFields;
    return this;
  }

   /**
   * Get manageCustomFields
   * @return manageCustomFields
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageCustomFields() {
    return manageCustomFields;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageCustomFields(Boolean manageCustomFields) {
    this.manageCustomFields = manageCustomFields;
  }


  public Role manageCustomNotifications(Boolean manageCustomNotifications) {
    this.manageCustomNotifications = manageCustomNotifications;
    return this;
  }

   /**
   * Get manageCustomNotifications
   * @return manageCustomNotifications
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_CUSTOM_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageCustomNotifications() {
    return manageCustomNotifications;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_CUSTOM_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageCustomNotifications(Boolean manageCustomNotifications) {
    this.manageCustomNotifications = manageCustomNotifications;
  }


  public Role manageEmailsTemplates(Boolean manageEmailsTemplates) {
    this.manageEmailsTemplates = manageEmailsTemplates;
    return this;
  }

   /**
   * Get manageEmailsTemplates
   * @return manageEmailsTemplates
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_EMAILS_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageEmailsTemplates() {
    return manageEmailsTemplates;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_EMAILS_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageEmailsTemplates(Boolean manageEmailsTemplates) {
    this.manageEmailsTemplates = manageEmailsTemplates;
  }


  public Role manageFolders(Boolean manageFolders) {
    this.manageFolders = manageFolders;
    return this;
  }

   /**
   * Get manageFolders
   * @return manageFolders
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_FOLDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageFolders() {
    return manageFolders;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_FOLDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageFolders(Boolean manageFolders) {
    this.manageFolders = manageFolders;
  }


  public Role manageIce(Boolean manageIce) {
    this.manageIce = manageIce;
    return this;
  }

   /**
   * Get manageIce
   * @return manageIce
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_ICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageIce() {
    return manageIce;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_ICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageIce(Boolean manageIce) {
    this.manageIce = manageIce;
  }


  public Role manageIdentities(Boolean manageIdentities) {
    this.manageIdentities = manageIdentities;
    return this;
  }

   /**
   * Get manageIdentities
   * @return manageIdentities
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_IDENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageIdentities() {
    return manageIdentities;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_IDENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageIdentities(Boolean manageIdentities) {
    this.manageIdentities = manageIdentities;
  }


  public Role manageMessaging(Boolean manageMessaging) {
    this.manageMessaging = manageMessaging;
    return this;
  }

   /**
   * Get manageMessaging
   * @return manageMessaging
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_MESSAGING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageMessaging() {
    return manageMessaging;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_MESSAGING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageMessaging(Boolean manageMessaging) {
    this.manageMessaging = manageMessaging;
  }


  public Role manageOwnNotifications(Boolean manageOwnNotifications) {
    this.manageOwnNotifications = manageOwnNotifications;
    return this;
  }

   /**
   * Get manageOwnNotifications
   * @return manageOwnNotifications
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_OWN_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageOwnNotifications() {
    return manageOwnNotifications;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_OWN_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageOwnNotifications(Boolean manageOwnNotifications) {
    this.manageOwnNotifications = manageOwnNotifications;
  }


  public Role manageReplyAssistant(Boolean manageReplyAssistant) {
    this.manageReplyAssistant = manageReplyAssistant;
    return this;
  }

   /**
   * Get manageReplyAssistant
   * @return manageReplyAssistant
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_REPLY_ASSISTANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageReplyAssistant() {
    return manageReplyAssistant;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_REPLY_ASSISTANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageReplyAssistant(Boolean manageReplyAssistant) {
    this.manageReplyAssistant = manageReplyAssistant;
  }


  public Role manageRoles(Boolean manageRoles) {
    this.manageRoles = manageRoles;
    return this;
  }

   /**
   * Get manageRoles
   * @return manageRoles
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageRoles() {
    return manageRoles;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageRoles(Boolean manageRoles) {
    this.manageRoles = manageRoles;
  }


  public Role manageRulesEngineRules(Boolean manageRulesEngineRules) {
    this.manageRulesEngineRules = manageRulesEngineRules;
    return this;
  }

   /**
   * Get manageRulesEngineRules
   * @return manageRulesEngineRules
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_RULES_ENGINE_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageRulesEngineRules() {
    return manageRulesEngineRules;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_RULES_ENGINE_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageRulesEngineRules(Boolean manageRulesEngineRules) {
    this.manageRulesEngineRules = manageRulesEngineRules;
  }


  public Role manageTags(Boolean manageTags) {
    this.manageTags = manageTags;
    return this;
  }

   /**
   * Get manageTags
   * @return manageTags
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageTags() {
    return manageTags;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageTags(Boolean manageTags) {
    this.manageTags = manageTags;
  }


  public Role manageTeams(Boolean manageTeams) {
    this.manageTeams = manageTeams;
    return this;
  }

   /**
   * Get manageTeams
   * @return manageTeams
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_TEAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageTeams() {
    return manageTeams;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_TEAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageTeams(Boolean manageTeams) {
    this.manageTeams = manageTeams;
  }


  public Role manageTopologies(Boolean manageTopologies) {
    this.manageTopologies = manageTopologies;
    return this;
  }

   /**
   * Get manageTopologies
   * @return manageTopologies
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_TOPOLOGIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageTopologies() {
    return manageTopologies;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_TOPOLOGIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageTopologies(Boolean manageTopologies) {
    this.manageTopologies = manageTopologies;
  }


  public Role manageUsersOfMyTeams(Boolean manageUsersOfMyTeams) {
    this.manageUsersOfMyTeams = manageUsersOfMyTeams;
    return this;
  }

   /**
   * Get manageUsersOfMyTeams
   * @return manageUsersOfMyTeams
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGE_USERS_OF_MY_TEAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageUsersOfMyTeams() {
    return manageUsersOfMyTeams;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_USERS_OF_MY_TEAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageUsersOfMyTeams(Boolean manageUsersOfMyTeams) {
    this.manageUsersOfMyTeams = manageUsersOfMyTeams;
  }


  public Role monitorTasks(Boolean monitorTasks) {
    this.monitorTasks = monitorTasks;
    return this;
  }

   /**
   * Get monitorTasks
   * @return monitorTasks
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MONITOR_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMonitorTasks() {
    return monitorTasks;
  }


  @JsonProperty(JSON_PROPERTY_MONITOR_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMonitorTasks(Boolean monitorTasks) {
    this.monitorTasks = monitorTasks;
  }


  public Role monitorTeamTasks(Boolean monitorTeamTasks) {
    this.monitorTeamTasks = monitorTeamTasks;
    return this;
  }

   /**
   * Get monitorTeamTasks
   * @return monitorTeamTasks
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MONITOR_TEAM_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMonitorTeamTasks() {
    return monitorTeamTasks;
  }


  @JsonProperty(JSON_PROPERTY_MONITOR_TEAM_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMonitorTeamTasks(Boolean monitorTeamTasks) {
    this.monitorTeamTasks = monitorTeamTasks;
  }


  public Role muteContent(Boolean muteContent) {
    this.muteContent = muteContent;
    return this;
  }

   /**
   * Get muteContent
   * @return muteContent
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MUTE_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMuteContent() {
    return muteContent;
  }


  @JsonProperty(JSON_PROPERTY_MUTE_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMuteContent(Boolean muteContent) {
    this.muteContent = muteContent;
  }


  public Role openContentThread(Boolean openContentThread) {
    this.openContentThread = openContentThread;
    return this;
  }

   /**
   * Get openContentThread
   * @return openContentThread
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPEN_CONTENT_THREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOpenContentThread() {
    return openContentThread;
  }


  @JsonProperty(JSON_PROPERTY_OPEN_CONTENT_THREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenContentThread(Boolean openContentThread) {
    this.openContentThread = openContentThread;
  }


  public Role publishContent(Boolean publishContent) {
    this.publishContent = publishContent;
    return this;
  }

   /**
   * Get publishContent
   * @return publishContent
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISH_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPublishContent() {
    return publishContent;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISH_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishContent(Boolean publishContent) {
    this.publishContent = publishContent;
  }


  public Role readCommunity(Boolean readCommunity) {
    this.readCommunity = readCommunity;
    return this;
  }

   /**
   * Get readCommunity
   * @return readCommunity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_COMMUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReadCommunity() {
    return readCommunity;
  }


  @JsonProperty(JSON_PROPERTY_READ_COMMUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadCommunity(Boolean readCommunity) {
    this.readCommunity = readCommunity;
  }


  public Role readContentSource(Boolean readContentSource) {
    this.readContentSource = readContentSource;
    return this;
  }

   /**
   * Get readContentSource
   * @return readContentSource
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_CONTENT_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReadContentSource() {
    return readContentSource;
  }


  @JsonProperty(JSON_PROPERTY_READ_CONTENT_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadContentSource(Boolean readContentSource) {
    this.readContentSource = readContentSource;
  }


  public Role readEvent(Boolean readEvent) {
    this.readEvent = readEvent;
    return this;
  }

   /**
   * Get readEvent
   * @return readEvent
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReadEvent() {
    return readEvent;
  }


  @JsonProperty(JSON_PROPERTY_READ_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadEvent(Boolean readEvent) {
    this.readEvent = readEvent;
  }


  public Role readExport(Boolean readExport) {
    this.readExport = readExport;
    return this;
  }

   /**
   * Get readExport
   * @return readExport
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_EXPORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReadExport() {
    return readExport;
  }


  @JsonProperty(JSON_PROPERTY_READ_EXPORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadExport(Boolean readExport) {
    this.readExport = readExport;
  }


  public Role readIdentity(Boolean readIdentity) {
    this.readIdentity = readIdentity;
    return this;
  }

   /**
   * Get readIdentity
   * @return readIdentity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReadIdentity() {
    return readIdentity;
  }


  @JsonProperty(JSON_PROPERTY_READ_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadIdentity(Boolean readIdentity) {
    this.readIdentity = readIdentity;
  }


  public Role readOwnStats(Boolean readOwnStats) {
    this.readOwnStats = readOwnStats;
    return this;
  }

   /**
   * Get readOwnStats
   * @return readOwnStats
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_OWN_STATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReadOwnStats() {
    return readOwnStats;
  }


  @JsonProperty(JSON_PROPERTY_READ_OWN_STATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadOwnStats(Boolean readOwnStats) {
    this.readOwnStats = readOwnStats;
  }


  public Role readPresence(Boolean readPresence) {
    this.readPresence = readPresence;
    return this;
  }

   /**
   * Get readPresence
   * @return readPresence
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_PRESENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReadPresence() {
    return readPresence;
  }


  @JsonProperty(JSON_PROPERTY_READ_PRESENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadPresence(Boolean readPresence) {
    this.readPresence = readPresence;
  }


  public Role readStats(Boolean readStats) {
    this.readStats = readStats;
    return this;
  }

   /**
   * Get readStats
   * @return readStats
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_STATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReadStats() {
    return readStats;
  }


  @JsonProperty(JSON_PROPERTY_READ_STATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadStats(Boolean readStats) {
    this.readStats = readStats;
  }


  public Role readUser(Boolean readUser) {
    this.readUser = readUser;
    return this;
  }

   /**
   * Get readUser
   * @return readUser
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_READ_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReadUser() {
    return readUser;
  }


  @JsonProperty(JSON_PROPERTY_READ_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadUser(Boolean readUser) {
    this.readUser = readUser;
  }


  public Role receiveTasks(Boolean receiveTasks) {
    this.receiveTasks = receiveTasks;
    return this;
  }

   /**
   * Get receiveTasks
   * @return receiveTasks
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECEIVE_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReceiveTasks() {
    return receiveTasks;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVE_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceiveTasks(Boolean receiveTasks) {
    this.receiveTasks = receiveTasks;
  }


  public Role replyWithAssistant(Boolean replyWithAssistant) {
    this.replyWithAssistant = replyWithAssistant;
    return this;
  }

   /**
   * Get replyWithAssistant
   * @return replyWithAssistant
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLY_WITH_ASSISTANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReplyWithAssistant() {
    return replyWithAssistant;
  }


  @JsonProperty(JSON_PROPERTY_REPLY_WITH_ASSISTANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplyWithAssistant(Boolean replyWithAssistant) {
    this.replyWithAssistant = replyWithAssistant;
  }


  public Role searchContents(Boolean searchContents) {
    this.searchContents = searchContents;
    return this;
  }

   /**
   * Get searchContents
   * @return searchContents
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEARCH_CONTENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSearchContents() {
    return searchContents;
  }


  @JsonProperty(JSON_PROPERTY_SEARCH_CONTENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchContents(Boolean searchContents) {
    this.searchContents = searchContents;
  }


  public Role searchEvent(Boolean searchEvent) {
    this.searchEvent = searchEvent;
    return this;
  }

   /**
   * Get searchEvent
   * @return searchEvent
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEARCH_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSearchEvent() {
    return searchEvent;
  }


  @JsonProperty(JSON_PROPERTY_SEARCH_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchEvent(Boolean searchEvent) {
    this.searchEvent = searchEvent;
  }


  public Role updateCommunity(Boolean updateCommunity) {
    this.updateCommunity = updateCommunity;
    return this;
  }

   /**
   * Get updateCommunity
   * @return updateCommunity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_COMMUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateCommunity() {
    return updateCommunity;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_COMMUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateCommunity(Boolean updateCommunity) {
    this.updateCommunity = updateCommunity;
  }


  public Role updateContentSource(Boolean updateContentSource) {
    this.updateContentSource = updateContentSource;
    return this;
  }

   /**
   * Get updateContentSource
   * @return updateContentSource
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_CONTENT_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateContentSource() {
    return updateContentSource;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_CONTENT_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateContentSource(Boolean updateContentSource) {
    this.updateContentSource = updateContentSource;
  }


  public Role updateExtension(Boolean updateExtension) {
    this.updateExtension = updateExtension;
    return this;
  }

   /**
   * Get updateExtension
   * @return updateExtension
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateExtension() {
    return updateExtension;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_EXTENSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateExtension(Boolean updateExtension) {
    this.updateExtension = updateExtension;
  }


  public Role updateIdentity(Boolean updateIdentity) {
    this.updateIdentity = updateIdentity;
    return this;
  }

   /**
   * Get updateIdentity
   * @return updateIdentity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateIdentity() {
    return updateIdentity;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateIdentity(Boolean updateIdentity) {
    this.updateIdentity = updateIdentity;
  }


  public Role updateIntervention(Boolean updateIntervention) {
    this.updateIntervention = updateIntervention;
    return this;
  }

   /**
   * Get updateIntervention
   * @return updateIntervention
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_INTERVENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateIntervention() {
    return updateIntervention;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_INTERVENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateIntervention(Boolean updateIntervention) {
    this.updateIntervention = updateIntervention;
  }


  public Role updateOwnIntervention(Boolean updateOwnIntervention) {
    this.updateOwnIntervention = updateOwnIntervention;
    return this;
  }

   /**
   * Get updateOwnIntervention
   * @return updateOwnIntervention
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_OWN_INTERVENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateOwnIntervention() {
    return updateOwnIntervention;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_OWN_INTERVENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateOwnIntervention(Boolean updateOwnIntervention) {
    this.updateOwnIntervention = updateOwnIntervention;
  }


  public Role updateSettings(Boolean updateSettings) {
    this.updateSettings = updateSettings;
    return this;
  }

   /**
   * Get updateSettings
   * @return updateSettings
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateSettings() {
    return updateSettings;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_SETTINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateSettings(Boolean updateSettings) {
    this.updateSettings = updateSettings;
  }


  public Role updateTimeSheet(Boolean updateTimeSheet) {
    this.updateTimeSheet = updateTimeSheet;
    return this;
  }

   /**
   * Get updateTimeSheet
   * @return updateTimeSheet
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME_SHEET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateTimeSheet() {
    return updateTimeSheet;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIME_SHEET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTimeSheet(Boolean updateTimeSheet) {
    this.updateTimeSheet = updateTimeSheet;
  }


  public Role updateUser(Boolean updateUser) {
    this.updateUser = updateUser;
    return this;
  }

   /**
   * Get updateUser
   * @return updateUser
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateUser() {
    return updateUser;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateUser(Boolean updateUser) {
    this.updateUser = updateUser;
  }


  public Role updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Role useCobrowsing(Boolean useCobrowsing) {
    this.useCobrowsing = useCobrowsing;
    return this;
  }

   /**
   * Get useCobrowsing
   * @return useCobrowsing
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USE_COBROWSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseCobrowsing() {
    return useCobrowsing;
  }


  @JsonProperty(JSON_PROPERTY_USE_COBROWSING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseCobrowsing(Boolean useCobrowsing) {
    this.useCobrowsing = useCobrowsing;
  }


  public Role useEmoji(Boolean useEmoji) {
    this.useEmoji = useEmoji;
    return this;
  }

   /**
   * Get useEmoji
   * @return useEmoji
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USE_EMOJI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseEmoji() {
    return useEmoji;
  }


  @JsonProperty(JSON_PROPERTY_USE_EMOJI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseEmoji(Boolean useEmoji) {
    this.useEmoji = useEmoji;
  }


  /**
   * Return true if this Role object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Role role = (Role) o;
    return Objects.equals(this.accessHelpCenter, role.accessHelpCenter) &&
        Objects.equals(this.accessPreviousMessages, role.accessPreviousMessages) &&
        Objects.equals(this.accessPullMode, role.accessPullMode) &&
        Objects.equals(this.adminStampAnswer, role.adminStampAnswer) &&
        Objects.equals(this.anonymizeIdentity, role.anonymizeIdentity) &&
        Objects.equals(this.approveContent, role.approveContent) &&
        Objects.equals(this.askAnExpert, role.askAnExpert) &&
        Objects.equals(this.assignIntervention, role.assignIntervention) &&
        Objects.equals(this.authorBlockContent, role.authorBlockContent) &&
        Objects.equals(this.closeContentThread, role.closeContentThread) &&
        Objects.equals(this.createAndDestroyExtension, role.createAndDestroyExtension) &&
        Objects.equals(this.createCommunity, role.createCommunity) &&
        Objects.equals(this.createContentSource, role.createContentSource) &&
        Objects.equals(this.createUser, role.createUser) &&
        Objects.equals(this.createdAt, role.createdAt) &&
        Objects.equals(this.delayExportContent, role.delayExportContent) &&
        Objects.equals(this.deleteContentThread, role.deleteContentThread) &&
        Objects.equals(this.escalateToVideo, role.escalateToVideo) &&
        Objects.equals(this.exportIdentity, role.exportIdentity) &&
        Objects.equals(this.id, role.id) &&
        Objects.equals(this.impersonateUser, role.impersonateUser) &&
        Objects.equals(this.inviteUser, role.inviteUser) &&
        Objects.equals(this.label, role.label) &&
        Objects.equals(this.lockIdentity, role.lockIdentity) &&
        Objects.equals(this.manageApiAccessTokens, role.manageApiAccessTokens) &&
        Objects.equals(this.manageAppSdkApplications, role.manageAppSdkApplications) &&
        Objects.equals(this.manageCategories, role.manageCategories) &&
        Objects.equals(this.manageChat, role.manageChat) &&
        Objects.equals(this.manageCustomFields, role.manageCustomFields) &&
        Objects.equals(this.manageCustomNotifications, role.manageCustomNotifications) &&
        Objects.equals(this.manageEmailsTemplates, role.manageEmailsTemplates) &&
        Objects.equals(this.manageFolders, role.manageFolders) &&
        Objects.equals(this.manageIce, role.manageIce) &&
        Objects.equals(this.manageIdentities, role.manageIdentities) &&
        Objects.equals(this.manageMessaging, role.manageMessaging) &&
        Objects.equals(this.manageOwnNotifications, role.manageOwnNotifications) &&
        Objects.equals(this.manageReplyAssistant, role.manageReplyAssistant) &&
        Objects.equals(this.manageRoles, role.manageRoles) &&
        Objects.equals(this.manageRulesEngineRules, role.manageRulesEngineRules) &&
        Objects.equals(this.manageTags, role.manageTags) &&
        Objects.equals(this.manageTeams, role.manageTeams) &&
        Objects.equals(this.manageTopologies, role.manageTopologies) &&
        Objects.equals(this.manageUsersOfMyTeams, role.manageUsersOfMyTeams) &&
        Objects.equals(this.monitorTasks, role.monitorTasks) &&
        Objects.equals(this.monitorTeamTasks, role.monitorTeamTasks) &&
        Objects.equals(this.muteContent, role.muteContent) &&
        Objects.equals(this.openContentThread, role.openContentThread) &&
        Objects.equals(this.publishContent, role.publishContent) &&
        Objects.equals(this.readCommunity, role.readCommunity) &&
        Objects.equals(this.readContentSource, role.readContentSource) &&
        Objects.equals(this.readEvent, role.readEvent) &&
        Objects.equals(this.readExport, role.readExport) &&
        Objects.equals(this.readIdentity, role.readIdentity) &&
        Objects.equals(this.readOwnStats, role.readOwnStats) &&
        Objects.equals(this.readPresence, role.readPresence) &&
        Objects.equals(this.readStats, role.readStats) &&
        Objects.equals(this.readUser, role.readUser) &&
        Objects.equals(this.receiveTasks, role.receiveTasks) &&
        Objects.equals(this.replyWithAssistant, role.replyWithAssistant) &&
        Objects.equals(this.searchContents, role.searchContents) &&
        Objects.equals(this.searchEvent, role.searchEvent) &&
        Objects.equals(this.updateCommunity, role.updateCommunity) &&
        Objects.equals(this.updateContentSource, role.updateContentSource) &&
        Objects.equals(this.updateExtension, role.updateExtension) &&
        Objects.equals(this.updateIdentity, role.updateIdentity) &&
        Objects.equals(this.updateIntervention, role.updateIntervention) &&
        Objects.equals(this.updateOwnIntervention, role.updateOwnIntervention) &&
        Objects.equals(this.updateSettings, role.updateSettings) &&
        Objects.equals(this.updateTimeSheet, role.updateTimeSheet) &&
        Objects.equals(this.updateUser, role.updateUser) &&
        Objects.equals(this.updatedAt, role.updatedAt) &&
        Objects.equals(this.useCobrowsing, role.useCobrowsing) &&
        Objects.equals(this.useEmoji, role.useEmoji);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessHelpCenter, accessPreviousMessages, accessPullMode, adminStampAnswer, anonymizeIdentity, approveContent, askAnExpert, assignIntervention, authorBlockContent, closeContentThread, createAndDestroyExtension, createCommunity, createContentSource, createUser, createdAt, delayExportContent, deleteContentThread, escalateToVideo, exportIdentity, id, impersonateUser, inviteUser, label, lockIdentity, manageApiAccessTokens, manageAppSdkApplications, manageCategories, manageChat, manageCustomFields, manageCustomNotifications, manageEmailsTemplates, manageFolders, manageIce, manageIdentities, manageMessaging, manageOwnNotifications, manageReplyAssistant, manageRoles, manageRulesEngineRules, manageTags, manageTeams, manageTopologies, manageUsersOfMyTeams, monitorTasks, monitorTeamTasks, muteContent, openContentThread, publishContent, readCommunity, readContentSource, readEvent, readExport, readIdentity, readOwnStats, readPresence, readStats, readUser, receiveTasks, replyWithAssistant, searchContents, searchEvent, updateCommunity, updateContentSource, updateExtension, updateIdentity, updateIntervention, updateOwnIntervention, updateSettings, updateTimeSheet, updateUser, updatedAt, useCobrowsing, useEmoji);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Role {\n");
    sb.append("    accessHelpCenter: ").append(toIndentedString(accessHelpCenter)).append("\n");
    sb.append("    accessPreviousMessages: ").append(toIndentedString(accessPreviousMessages)).append("\n");
    sb.append("    accessPullMode: ").append(toIndentedString(accessPullMode)).append("\n");
    sb.append("    adminStampAnswer: ").append(toIndentedString(adminStampAnswer)).append("\n");
    sb.append("    anonymizeIdentity: ").append(toIndentedString(anonymizeIdentity)).append("\n");
    sb.append("    approveContent: ").append(toIndentedString(approveContent)).append("\n");
    sb.append("    askAnExpert: ").append(toIndentedString(askAnExpert)).append("\n");
    sb.append("    assignIntervention: ").append(toIndentedString(assignIntervention)).append("\n");
    sb.append("    authorBlockContent: ").append(toIndentedString(authorBlockContent)).append("\n");
    sb.append("    closeContentThread: ").append(toIndentedString(closeContentThread)).append("\n");
    sb.append("    createAndDestroyExtension: ").append(toIndentedString(createAndDestroyExtension)).append("\n");
    sb.append("    createCommunity: ").append(toIndentedString(createCommunity)).append("\n");
    sb.append("    createContentSource: ").append(toIndentedString(createContentSource)).append("\n");
    sb.append("    createUser: ").append(toIndentedString(createUser)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    delayExportContent: ").append(toIndentedString(delayExportContent)).append("\n");
    sb.append("    deleteContentThread: ").append(toIndentedString(deleteContentThread)).append("\n");
    sb.append("    escalateToVideo: ").append(toIndentedString(escalateToVideo)).append("\n");
    sb.append("    exportIdentity: ").append(toIndentedString(exportIdentity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    impersonateUser: ").append(toIndentedString(impersonateUser)).append("\n");
    sb.append("    inviteUser: ").append(toIndentedString(inviteUser)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    lockIdentity: ").append(toIndentedString(lockIdentity)).append("\n");
    sb.append("    manageApiAccessTokens: ").append(toIndentedString(manageApiAccessTokens)).append("\n");
    sb.append("    manageAppSdkApplications: ").append(toIndentedString(manageAppSdkApplications)).append("\n");
    sb.append("    manageCategories: ").append(toIndentedString(manageCategories)).append("\n");
    sb.append("    manageChat: ").append(toIndentedString(manageChat)).append("\n");
    sb.append("    manageCustomFields: ").append(toIndentedString(manageCustomFields)).append("\n");
    sb.append("    manageCustomNotifications: ").append(toIndentedString(manageCustomNotifications)).append("\n");
    sb.append("    manageEmailsTemplates: ").append(toIndentedString(manageEmailsTemplates)).append("\n");
    sb.append("    manageFolders: ").append(toIndentedString(manageFolders)).append("\n");
    sb.append("    manageIce: ").append(toIndentedString(manageIce)).append("\n");
    sb.append("    manageIdentities: ").append(toIndentedString(manageIdentities)).append("\n");
    sb.append("    manageMessaging: ").append(toIndentedString(manageMessaging)).append("\n");
    sb.append("    manageOwnNotifications: ").append(toIndentedString(manageOwnNotifications)).append("\n");
    sb.append("    manageReplyAssistant: ").append(toIndentedString(manageReplyAssistant)).append("\n");
    sb.append("    manageRoles: ").append(toIndentedString(manageRoles)).append("\n");
    sb.append("    manageRulesEngineRules: ").append(toIndentedString(manageRulesEngineRules)).append("\n");
    sb.append("    manageTags: ").append(toIndentedString(manageTags)).append("\n");
    sb.append("    manageTeams: ").append(toIndentedString(manageTeams)).append("\n");
    sb.append("    manageTopologies: ").append(toIndentedString(manageTopologies)).append("\n");
    sb.append("    manageUsersOfMyTeams: ").append(toIndentedString(manageUsersOfMyTeams)).append("\n");
    sb.append("    monitorTasks: ").append(toIndentedString(monitorTasks)).append("\n");
    sb.append("    monitorTeamTasks: ").append(toIndentedString(monitorTeamTasks)).append("\n");
    sb.append("    muteContent: ").append(toIndentedString(muteContent)).append("\n");
    sb.append("    openContentThread: ").append(toIndentedString(openContentThread)).append("\n");
    sb.append("    publishContent: ").append(toIndentedString(publishContent)).append("\n");
    sb.append("    readCommunity: ").append(toIndentedString(readCommunity)).append("\n");
    sb.append("    readContentSource: ").append(toIndentedString(readContentSource)).append("\n");
    sb.append("    readEvent: ").append(toIndentedString(readEvent)).append("\n");
    sb.append("    readExport: ").append(toIndentedString(readExport)).append("\n");
    sb.append("    readIdentity: ").append(toIndentedString(readIdentity)).append("\n");
    sb.append("    readOwnStats: ").append(toIndentedString(readOwnStats)).append("\n");
    sb.append("    readPresence: ").append(toIndentedString(readPresence)).append("\n");
    sb.append("    readStats: ").append(toIndentedString(readStats)).append("\n");
    sb.append("    readUser: ").append(toIndentedString(readUser)).append("\n");
    sb.append("    receiveTasks: ").append(toIndentedString(receiveTasks)).append("\n");
    sb.append("    replyWithAssistant: ").append(toIndentedString(replyWithAssistant)).append("\n");
    sb.append("    searchContents: ").append(toIndentedString(searchContents)).append("\n");
    sb.append("    searchEvent: ").append(toIndentedString(searchEvent)).append("\n");
    sb.append("    updateCommunity: ").append(toIndentedString(updateCommunity)).append("\n");
    sb.append("    updateContentSource: ").append(toIndentedString(updateContentSource)).append("\n");
    sb.append("    updateExtension: ").append(toIndentedString(updateExtension)).append("\n");
    sb.append("    updateIdentity: ").append(toIndentedString(updateIdentity)).append("\n");
    sb.append("    updateIntervention: ").append(toIndentedString(updateIntervention)).append("\n");
    sb.append("    updateOwnIntervention: ").append(toIndentedString(updateOwnIntervention)).append("\n");
    sb.append("    updateSettings: ").append(toIndentedString(updateSettings)).append("\n");
    sb.append("    updateTimeSheet: ").append(toIndentedString(updateTimeSheet)).append("\n");
    sb.append("    updateUser: ").append(toIndentedString(updateUser)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    useCobrowsing: ").append(toIndentedString(useCobrowsing)).append("\n");
    sb.append("    useEmoji: ").append(toIndentedString(useEmoji)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

