/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.JSON;


/**
 * Settings
 */
@JsonPropertyOrder({
  Settings.JSON_PROPERTY_ACTIVITY_PRESENCE_THRESHOLD,
  Settings.JSON_PROPERTY_ACTIVITY_TRACKING,
  Settings.JSON_PROPERTY_BEGINNING_OF_WEEK,
  Settings.JSON_PROPERTY_BROWSER_NOTIFICATIONS_DISABLED,
  Settings.JSON_PROPERTY_CONTENT_LANGUAGES,
  Settings.JSON_PROPERTY_CREATED_AT,
  Settings.JSON_PROPERTY_DENY_IFRAME_INTEGRATION,
  Settings.JSON_PROPERTY_DISABLE_PASSWORD_AUTOCOMPLETE,
  Settings.JSON_PROPERTY_DISPLAY_ONLY_UNKNOWN_BBCODE,
  Settings.JSON_PROPERTY_DUMP_IN_PREPROD,
  Settings.JSON_PROPERTY_ENABLE_AUTO_SCROLL_DOWN,
  Settings.JSON_PROPERTY_EXPIRE_PASSWORD_AFTER,
  Settings.JSON_PROPERTY_EXPIRE_PASSWORD_ENABLED,
  Settings.JSON_PROPERTY_FTE_DURATION,
  Settings.JSON_PROPERTY_ID,
  Settings.JSON_PROPERTY_IDENTITY_MERGE,
  Settings.JSON_PROPERTY_INTERVENTION_CLOSING_PERIOD,
  Settings.JSON_PROPERTY_INTERVENTION_DEFER_RATES,
  Settings.JSON_PROPERTY_INTERVENTION_DEFER_THRESHOLD,
  Settings.JSON_PROPERTY_INTERVENTION_RATES,
  Settings.JSON_PROPERTY_LOCALE,
  Settings.JSON_PROPERTY_MULTI_LANG,
  Settings.JSON_PROPERTY_NAME,
  Settings.JSON_PROPERTY_PASSWORD_ARCHIVABLE_ENABLED,
  Settings.JSON_PROPERTY_PASSWORD_ARCHIVABLE_SIZE,
  Settings.JSON_PROPERTY_PASSWORD_MIN_LENGTH,
  Settings.JSON_PROPERTY_PASSWORD_NON_WORD,
  Settings.JSON_PROPERTY_PASSWORD_NUMBERS,
  Settings.JSON_PROPERTY_PASSWORD_RECOVERY_DISABLED,
  Settings.JSON_PROPERTY_PUSH_ENABLED,
  Settings.JSON_PROPERTY_REPLY_AS_ANY_IDENTITY,
  Settings.JSON_PROPERTY_RTL_SUPPORT,
  Settings.JSON_PROPERTY_SELF_APPROVAL_REQUIRED,
  Settings.JSON_PROPERTY_SESSION_TIMEOUT,
  Settings.JSON_PROPERTY_SHARDING_KEY,
  Settings.JSON_PROPERTY_SPELLCHECKING,
  Settings.JSON_PROPERTY_STYLE,
  Settings.JSON_PROPERTY_THIRD_PARTY_SERVICES_DISABLED,
  Settings.JSON_PROPERTY_TIMEZONE,
  Settings.JSON_PROPERTY_TYPE,
  Settings.JSON_PROPERTY_UPDATED_AT,
  Settings.JSON_PROPERTY_URGENT_TASK_THRESHOLD,
  Settings.JSON_PROPERTY_USE_TWO_LETTERS_AVATARS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-03-13T22:37:55.741968+01:00[Europe/Paris]")
public class Settings implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ACTIVITY_PRESENCE_THRESHOLD = "activity_presence_threshold";
  private Integer activityPresenceThreshold;

  public static final String JSON_PROPERTY_ACTIVITY_TRACKING = "activity_tracking";
  private Boolean activityTracking;

  public static final String JSON_PROPERTY_BEGINNING_OF_WEEK = "beginning_of_week";
  private String beginningOfWeek;

  public static final String JSON_PROPERTY_BROWSER_NOTIFICATIONS_DISABLED = "browser_notifications_disabled";
  private Boolean browserNotificationsDisabled;

  public static final String JSON_PROPERTY_CONTENT_LANGUAGES = "content_languages[]";
  private List<String> contentLanguages = null;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_DENY_IFRAME_INTEGRATION = "deny_iframe_integration";
  private Boolean denyIframeIntegration;

  public static final String JSON_PROPERTY_DISABLE_PASSWORD_AUTOCOMPLETE = "disable_password_autocomplete";
  private Boolean disablePasswordAutocomplete;

  public static final String JSON_PROPERTY_DISPLAY_ONLY_UNKNOWN_BBCODE = "display_only_unknown_bbcode";
  private Boolean displayOnlyUnknownBbcode;

  public static final String JSON_PROPERTY_DUMP_IN_PREPROD = "dump_in_preprod";
  private Boolean dumpInPreprod;

  public static final String JSON_PROPERTY_ENABLE_AUTO_SCROLL_DOWN = "enable_auto_scroll_down";
  private Boolean enableAutoScrollDown;

  public static final String JSON_PROPERTY_EXPIRE_PASSWORD_AFTER = "expire_password_after";
  private Integer expirePasswordAfter;

  public static final String JSON_PROPERTY_EXPIRE_PASSWORD_ENABLED = "expire_password_enabled";
  private Boolean expirePasswordEnabled;

  public static final String JSON_PROPERTY_FTE_DURATION = "fte_duration";
  private Integer fteDuration;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_IDENTITY_MERGE = "identity_merge";
  private Boolean identityMerge;

  public static final String JSON_PROPERTY_INTERVENTION_CLOSING_PERIOD = "intervention_closing_period";
  private Integer interventionClosingPeriod;

  public static final String JSON_PROPERTY_INTERVENTION_DEFER_RATES = "intervention_defer_rates";
  private List<Integer> interventionDeferRates = null;

  public static final String JSON_PROPERTY_INTERVENTION_DEFER_THRESHOLD = "intervention_defer_threshold";
  private Integer interventionDeferThreshold;

  public static final String JSON_PROPERTY_INTERVENTION_RATES = "intervention_rates";
  private List<Integer> interventionRates = null;

  public static final String JSON_PROPERTY_LOCALE = "locale";
  private String locale;

  public static final String JSON_PROPERTY_MULTI_LANG = "multi_lang";
  private Boolean multiLang;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PASSWORD_ARCHIVABLE_ENABLED = "password_archivable_enabled";
  private Boolean passwordArchivableEnabled;

  public static final String JSON_PROPERTY_PASSWORD_ARCHIVABLE_SIZE = "password_archivable_size";
  private Integer passwordArchivableSize;

  public static final String JSON_PROPERTY_PASSWORD_MIN_LENGTH = "password_min_length";
  private Integer passwordMinLength;

  public static final String JSON_PROPERTY_PASSWORD_NON_WORD = "password_non_word";
  private Boolean passwordNonWord;

  public static final String JSON_PROPERTY_PASSWORD_NUMBERS = "password_numbers";
  private Boolean passwordNumbers;

  public static final String JSON_PROPERTY_PASSWORD_RECOVERY_DISABLED = "password_recovery_disabled";
  private Boolean passwordRecoveryDisabled;

  public static final String JSON_PROPERTY_PUSH_ENABLED = "push_enabled";
  private Boolean pushEnabled;

  public static final String JSON_PROPERTY_REPLY_AS_ANY_IDENTITY = "reply_as_any_identity";
  private Boolean replyAsAnyIdentity;

  public static final String JSON_PROPERTY_RTL_SUPPORT = "rtl_support";
  private Boolean rtlSupport;

  public static final String JSON_PROPERTY_SELF_APPROVAL_REQUIRED = "self_approval_required";
  private Boolean selfApprovalRequired;

  public static final String JSON_PROPERTY_SESSION_TIMEOUT = "session_timeout";
  private Integer sessionTimeout;

  public static final String JSON_PROPERTY_SHARDING_KEY = "sharding_key";
  private String shardingKey;

  public static final String JSON_PROPERTY_SPELLCHECKING = "spellchecking";
  private Boolean spellchecking;

  public static final String JSON_PROPERTY_STYLE = "style";
  private String style;

  public static final String JSON_PROPERTY_THIRD_PARTY_SERVICES_DISABLED = "third_party_services_disabled";
  private Boolean thirdPartyServicesDisabled;

  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  private String timezone;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_URGENT_TASK_THRESHOLD = "urgent_task_threshold";
  private Integer urgentTaskThreshold;

  public static final String JSON_PROPERTY_USE_TWO_LETTERS_AVATARS = "use_two_letters_avatars";
  private Boolean useTwoLettersAvatars;

  public Settings() { 
  }

  public Settings activityPresenceThreshold(Integer activityPresenceThreshold) {
    this.activityPresenceThreshold = activityPresenceThreshold;
    return this;
  }

   /**
   * Get activityPresenceThreshold
   * @return activityPresenceThreshold
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVITY_PRESENCE_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getActivityPresenceThreshold() {
    return activityPresenceThreshold;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVITY_PRESENCE_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivityPresenceThreshold(Integer activityPresenceThreshold) {
    this.activityPresenceThreshold = activityPresenceThreshold;
  }


  public Settings activityTracking(Boolean activityTracking) {
    this.activityTracking = activityTracking;
    return this;
  }

   /**
   * Get activityTracking
   * @return activityTracking
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVITY_TRACKING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActivityTracking() {
    return activityTracking;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVITY_TRACKING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivityTracking(Boolean activityTracking) {
    this.activityTracking = activityTracking;
  }


  public Settings beginningOfWeek(String beginningOfWeek) {
    this.beginningOfWeek = beginningOfWeek;
    return this;
  }

   /**
   * Get beginningOfWeek
   * @return beginningOfWeek
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BEGINNING_OF_WEEK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBeginningOfWeek() {
    return beginningOfWeek;
  }


  @JsonProperty(JSON_PROPERTY_BEGINNING_OF_WEEK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeginningOfWeek(String beginningOfWeek) {
    this.beginningOfWeek = beginningOfWeek;
  }


  public Settings browserNotificationsDisabled(Boolean browserNotificationsDisabled) {
    this.browserNotificationsDisabled = browserNotificationsDisabled;
    return this;
  }

   /**
   * Get browserNotificationsDisabled
   * @return browserNotificationsDisabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BROWSER_NOTIFICATIONS_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBrowserNotificationsDisabled() {
    return browserNotificationsDisabled;
  }


  @JsonProperty(JSON_PROPERTY_BROWSER_NOTIFICATIONS_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrowserNotificationsDisabled(Boolean browserNotificationsDisabled) {
    this.browserNotificationsDisabled = browserNotificationsDisabled;
  }


  public Settings contentLanguages(List<String> contentLanguages) {
    this.contentLanguages = contentLanguages;
    return this;
  }

  public Settings addContentLanguagesItem(String contentLanguagesItem) {
    if (this.contentLanguages == null) {
      this.contentLanguages = new ArrayList<>();
    }
    this.contentLanguages.add(contentLanguagesItem);
    return this;
  }

   /**
   * Get contentLanguages
   * @return contentLanguages
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT_LANGUAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getContentLanguages() {
    return contentLanguages;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_LANGUAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentLanguages(List<String> contentLanguages) {
    this.contentLanguages = contentLanguages;
  }


  public Settings createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Settings denyIframeIntegration(Boolean denyIframeIntegration) {
    this.denyIframeIntegration = denyIframeIntegration;
    return this;
  }

   /**
   * Get denyIframeIntegration
   * @return denyIframeIntegration
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DENY_IFRAME_INTEGRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDenyIframeIntegration() {
    return denyIframeIntegration;
  }


  @JsonProperty(JSON_PROPERTY_DENY_IFRAME_INTEGRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDenyIframeIntegration(Boolean denyIframeIntegration) {
    this.denyIframeIntegration = denyIframeIntegration;
  }


  public Settings disablePasswordAutocomplete(Boolean disablePasswordAutocomplete) {
    this.disablePasswordAutocomplete = disablePasswordAutocomplete;
    return this;
  }

   /**
   * Get disablePasswordAutocomplete
   * @return disablePasswordAutocomplete
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISABLE_PASSWORD_AUTOCOMPLETE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisablePasswordAutocomplete() {
    return disablePasswordAutocomplete;
  }


  @JsonProperty(JSON_PROPERTY_DISABLE_PASSWORD_AUTOCOMPLETE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisablePasswordAutocomplete(Boolean disablePasswordAutocomplete) {
    this.disablePasswordAutocomplete = disablePasswordAutocomplete;
  }


  public Settings displayOnlyUnknownBbcode(Boolean displayOnlyUnknownBbcode) {
    this.displayOnlyUnknownBbcode = displayOnlyUnknownBbcode;
    return this;
  }

   /**
   * Get displayOnlyUnknownBbcode
   * @return displayOnlyUnknownBbcode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_ONLY_UNKNOWN_BBCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisplayOnlyUnknownBbcode() {
    return displayOnlyUnknownBbcode;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_ONLY_UNKNOWN_BBCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayOnlyUnknownBbcode(Boolean displayOnlyUnknownBbcode) {
    this.displayOnlyUnknownBbcode = displayOnlyUnknownBbcode;
  }


  public Settings dumpInPreprod(Boolean dumpInPreprod) {
    this.dumpInPreprod = dumpInPreprod;
    return this;
  }

   /**
   * Get dumpInPreprod
   * @return dumpInPreprod
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DUMP_IN_PREPROD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDumpInPreprod() {
    return dumpInPreprod;
  }


  @JsonProperty(JSON_PROPERTY_DUMP_IN_PREPROD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDumpInPreprod(Boolean dumpInPreprod) {
    this.dumpInPreprod = dumpInPreprod;
  }


  public Settings enableAutoScrollDown(Boolean enableAutoScrollDown) {
    this.enableAutoScrollDown = enableAutoScrollDown;
    return this;
  }

   /**
   * Get enableAutoScrollDown
   * @return enableAutoScrollDown
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLE_AUTO_SCROLL_DOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnableAutoScrollDown() {
    return enableAutoScrollDown;
  }


  @JsonProperty(JSON_PROPERTY_ENABLE_AUTO_SCROLL_DOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnableAutoScrollDown(Boolean enableAutoScrollDown) {
    this.enableAutoScrollDown = enableAutoScrollDown;
  }


  public Settings expirePasswordAfter(Integer expirePasswordAfter) {
    this.expirePasswordAfter = expirePasswordAfter;
    return this;
  }

   /**
   * Get expirePasswordAfter
   * @return expirePasswordAfter
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRE_PASSWORD_AFTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExpirePasswordAfter() {
    return expirePasswordAfter;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRE_PASSWORD_AFTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpirePasswordAfter(Integer expirePasswordAfter) {
    this.expirePasswordAfter = expirePasswordAfter;
  }


  public Settings expirePasswordEnabled(Boolean expirePasswordEnabled) {
    this.expirePasswordEnabled = expirePasswordEnabled;
    return this;
  }

   /**
   * Get expirePasswordEnabled
   * @return expirePasswordEnabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRE_PASSWORD_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getExpirePasswordEnabled() {
    return expirePasswordEnabled;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRE_PASSWORD_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpirePasswordEnabled(Boolean expirePasswordEnabled) {
    this.expirePasswordEnabled = expirePasswordEnabled;
  }


  public Settings fteDuration(Integer fteDuration) {
    this.fteDuration = fteDuration;
    return this;
  }

   /**
   * Get fteDuration
   * @return fteDuration
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FTE_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFteDuration() {
    return fteDuration;
  }


  @JsonProperty(JSON_PROPERTY_FTE_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFteDuration(Integer fteDuration) {
    this.fteDuration = fteDuration;
  }


  public Settings id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public Settings identityMerge(Boolean identityMerge) {
    this.identityMerge = identityMerge;
    return this;
  }

   /**
   * Get identityMerge
   * @return identityMerge
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTITY_MERGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIdentityMerge() {
    return identityMerge;
  }


  @JsonProperty(JSON_PROPERTY_IDENTITY_MERGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentityMerge(Boolean identityMerge) {
    this.identityMerge = identityMerge;
  }


  public Settings interventionClosingPeriod(Integer interventionClosingPeriod) {
    this.interventionClosingPeriod = interventionClosingPeriod;
    return this;
  }

   /**
   * Get interventionClosingPeriod
   * @return interventionClosingPeriod
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERVENTION_CLOSING_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInterventionClosingPeriod() {
    return interventionClosingPeriod;
  }


  @JsonProperty(JSON_PROPERTY_INTERVENTION_CLOSING_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterventionClosingPeriod(Integer interventionClosingPeriod) {
    this.interventionClosingPeriod = interventionClosingPeriod;
  }


  public Settings interventionDeferRates(List<Integer> interventionDeferRates) {
    this.interventionDeferRates = interventionDeferRates;
    return this;
  }

  public Settings addInterventionDeferRatesItem(Integer interventionDeferRatesItem) {
    if (this.interventionDeferRates == null) {
      this.interventionDeferRates = new ArrayList<>();
    }
    this.interventionDeferRates.add(interventionDeferRatesItem);
    return this;
  }

   /**
   * Get interventionDeferRates
   * @return interventionDeferRates
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERVENTION_DEFER_RATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getInterventionDeferRates() {
    return interventionDeferRates;
  }


  @JsonProperty(JSON_PROPERTY_INTERVENTION_DEFER_RATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterventionDeferRates(List<Integer> interventionDeferRates) {
    this.interventionDeferRates = interventionDeferRates;
  }


  public Settings interventionDeferThreshold(Integer interventionDeferThreshold) {
    this.interventionDeferThreshold = interventionDeferThreshold;
    return this;
  }

   /**
   * Get interventionDeferThreshold
   * @return interventionDeferThreshold
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERVENTION_DEFER_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInterventionDeferThreshold() {
    return interventionDeferThreshold;
  }


  @JsonProperty(JSON_PROPERTY_INTERVENTION_DEFER_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterventionDeferThreshold(Integer interventionDeferThreshold) {
    this.interventionDeferThreshold = interventionDeferThreshold;
  }


  public Settings interventionRates(List<Integer> interventionRates) {
    this.interventionRates = interventionRates;
    return this;
  }

  public Settings addInterventionRatesItem(Integer interventionRatesItem) {
    if (this.interventionRates == null) {
      this.interventionRates = new ArrayList<>();
    }
    this.interventionRates.add(interventionRatesItem);
    return this;
  }

   /**
   * Get interventionRates
   * @return interventionRates
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERVENTION_RATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getInterventionRates() {
    return interventionRates;
  }


  @JsonProperty(JSON_PROPERTY_INTERVENTION_RATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterventionRates(List<Integer> interventionRates) {
    this.interventionRates = interventionRates;
  }


  public Settings locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocale() {
    return locale;
  }


  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocale(String locale) {
    this.locale = locale;
  }


  public Settings multiLang(Boolean multiLang) {
    this.multiLang = multiLang;
    return this;
  }

   /**
   * Get multiLang
   * @return multiLang
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MULTI_LANG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMultiLang() {
    return multiLang;
  }


  @JsonProperty(JSON_PROPERTY_MULTI_LANG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMultiLang(Boolean multiLang) {
    this.multiLang = multiLang;
  }


  public Settings name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public Settings passwordArchivableEnabled(Boolean passwordArchivableEnabled) {
    this.passwordArchivableEnabled = passwordArchivableEnabled;
    return this;
  }

   /**
   * Get passwordArchivableEnabled
   * @return passwordArchivableEnabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD_ARCHIVABLE_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPasswordArchivableEnabled() {
    return passwordArchivableEnabled;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD_ARCHIVABLE_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPasswordArchivableEnabled(Boolean passwordArchivableEnabled) {
    this.passwordArchivableEnabled = passwordArchivableEnabled;
  }


  public Settings passwordArchivableSize(Integer passwordArchivableSize) {
    this.passwordArchivableSize = passwordArchivableSize;
    return this;
  }

   /**
   * Get passwordArchivableSize
   * @return passwordArchivableSize
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD_ARCHIVABLE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPasswordArchivableSize() {
    return passwordArchivableSize;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD_ARCHIVABLE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPasswordArchivableSize(Integer passwordArchivableSize) {
    this.passwordArchivableSize = passwordArchivableSize;
  }


  public Settings passwordMinLength(Integer passwordMinLength) {
    this.passwordMinLength = passwordMinLength;
    return this;
  }

   /**
   * Get passwordMinLength
   * @return passwordMinLength
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD_MIN_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPasswordMinLength() {
    return passwordMinLength;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD_MIN_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPasswordMinLength(Integer passwordMinLength) {
    this.passwordMinLength = passwordMinLength;
  }


  public Settings passwordNonWord(Boolean passwordNonWord) {
    this.passwordNonWord = passwordNonWord;
    return this;
  }

   /**
   * Get passwordNonWord
   * @return passwordNonWord
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD_NON_WORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPasswordNonWord() {
    return passwordNonWord;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD_NON_WORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPasswordNonWord(Boolean passwordNonWord) {
    this.passwordNonWord = passwordNonWord;
  }


  public Settings passwordNumbers(Boolean passwordNumbers) {
    this.passwordNumbers = passwordNumbers;
    return this;
  }

   /**
   * Get passwordNumbers
   * @return passwordNumbers
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPasswordNumbers() {
    return passwordNumbers;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPasswordNumbers(Boolean passwordNumbers) {
    this.passwordNumbers = passwordNumbers;
  }


  public Settings passwordRecoveryDisabled(Boolean passwordRecoveryDisabled) {
    this.passwordRecoveryDisabled = passwordRecoveryDisabled;
    return this;
  }

   /**
   * Get passwordRecoveryDisabled
   * @return passwordRecoveryDisabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD_RECOVERY_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPasswordRecoveryDisabled() {
    return passwordRecoveryDisabled;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD_RECOVERY_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPasswordRecoveryDisabled(Boolean passwordRecoveryDisabled) {
    this.passwordRecoveryDisabled = passwordRecoveryDisabled;
  }


  public Settings pushEnabled(Boolean pushEnabled) {
    this.pushEnabled = pushEnabled;
    return this;
  }

   /**
   * Get pushEnabled
   * @return pushEnabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUSH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPushEnabled() {
    return pushEnabled;
  }


  @JsonProperty(JSON_PROPERTY_PUSH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPushEnabled(Boolean pushEnabled) {
    this.pushEnabled = pushEnabled;
  }


  public Settings replyAsAnyIdentity(Boolean replyAsAnyIdentity) {
    this.replyAsAnyIdentity = replyAsAnyIdentity;
    return this;
  }

   /**
   * Get replyAsAnyIdentity
   * @return replyAsAnyIdentity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLY_AS_ANY_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReplyAsAnyIdentity() {
    return replyAsAnyIdentity;
  }


  @JsonProperty(JSON_PROPERTY_REPLY_AS_ANY_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplyAsAnyIdentity(Boolean replyAsAnyIdentity) {
    this.replyAsAnyIdentity = replyAsAnyIdentity;
  }


  public Settings rtlSupport(Boolean rtlSupport) {
    this.rtlSupport = rtlSupport;
    return this;
  }

   /**
   * Get rtlSupport
   * @return rtlSupport
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RTL_SUPPORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRtlSupport() {
    return rtlSupport;
  }


  @JsonProperty(JSON_PROPERTY_RTL_SUPPORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRtlSupport(Boolean rtlSupport) {
    this.rtlSupport = rtlSupport;
  }


  public Settings selfApprovalRequired(Boolean selfApprovalRequired) {
    this.selfApprovalRequired = selfApprovalRequired;
    return this;
  }

   /**
   * Get selfApprovalRequired
   * @return selfApprovalRequired
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELF_APPROVAL_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSelfApprovalRequired() {
    return selfApprovalRequired;
  }


  @JsonProperty(JSON_PROPERTY_SELF_APPROVAL_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelfApprovalRequired(Boolean selfApprovalRequired) {
    this.selfApprovalRequired = selfApprovalRequired;
  }


  public Settings sessionTimeout(Integer sessionTimeout) {
    this.sessionTimeout = sessionTimeout;
    return this;
  }

   /**
   * Get sessionTimeout
   * @return sessionTimeout
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSessionTimeout() {
    return sessionTimeout;
  }


  @JsonProperty(JSON_PROPERTY_SESSION_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionTimeout(Integer sessionTimeout) {
    this.sessionTimeout = sessionTimeout;
  }


  public Settings shardingKey(String shardingKey) {
    this.shardingKey = shardingKey;
    return this;
  }

   /**
   * Get shardingKey
   * @return shardingKey
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARDING_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShardingKey() {
    return shardingKey;
  }


  @JsonProperty(JSON_PROPERTY_SHARDING_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShardingKey(String shardingKey) {
    this.shardingKey = shardingKey;
  }


  public Settings spellchecking(Boolean spellchecking) {
    this.spellchecking = spellchecking;
    return this;
  }

   /**
   * Get spellchecking
   * @return spellchecking
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPELLCHECKING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSpellchecking() {
    return spellchecking;
  }


  @JsonProperty(JSON_PROPERTY_SPELLCHECKING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpellchecking(Boolean spellchecking) {
    this.spellchecking = spellchecking;
  }


  public Settings style(String style) {
    this.style = style;
    return this;
  }

   /**
   * Get style
   * @return style
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStyle() {
    return style;
  }


  @JsonProperty(JSON_PROPERTY_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStyle(String style) {
    this.style = style;
  }


  public Settings thirdPartyServicesDisabled(Boolean thirdPartyServicesDisabled) {
    this.thirdPartyServicesDisabled = thirdPartyServicesDisabled;
    return this;
  }

   /**
   * Get thirdPartyServicesDisabled
   * @return thirdPartyServicesDisabled
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THIRD_PARTY_SERVICES_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getThirdPartyServicesDisabled() {
    return thirdPartyServicesDisabled;
  }


  @JsonProperty(JSON_PROPERTY_THIRD_PARTY_SERVICES_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThirdPartyServicesDisabled(Boolean thirdPartyServicesDisabled) {
    this.thirdPartyServicesDisabled = thirdPartyServicesDisabled;
  }


  public Settings timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimezone() {
    return timezone;
  }


  @JsonProperty(JSON_PROPERTY_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  public Settings type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public Settings updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Settings urgentTaskThreshold(Integer urgentTaskThreshold) {
    this.urgentTaskThreshold = urgentTaskThreshold;
    return this;
  }

   /**
   * Get urgentTaskThreshold
   * @return urgentTaskThreshold
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URGENT_TASK_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUrgentTaskThreshold() {
    return urgentTaskThreshold;
  }


  @JsonProperty(JSON_PROPERTY_URGENT_TASK_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrgentTaskThreshold(Integer urgentTaskThreshold) {
    this.urgentTaskThreshold = urgentTaskThreshold;
  }


  public Settings useTwoLettersAvatars(Boolean useTwoLettersAvatars) {
    this.useTwoLettersAvatars = useTwoLettersAvatars;
    return this;
  }

   /**
   * Get useTwoLettersAvatars
   * @return useTwoLettersAvatars
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USE_TWO_LETTERS_AVATARS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseTwoLettersAvatars() {
    return useTwoLettersAvatars;
  }


  @JsonProperty(JSON_PROPERTY_USE_TWO_LETTERS_AVATARS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseTwoLettersAvatars(Boolean useTwoLettersAvatars) {
    this.useTwoLettersAvatars = useTwoLettersAvatars;
  }


  /**
   * Return true if this Settings object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Settings settings = (Settings) o;
    return Objects.equals(this.activityPresenceThreshold, settings.activityPresenceThreshold) &&
        Objects.equals(this.activityTracking, settings.activityTracking) &&
        Objects.equals(this.beginningOfWeek, settings.beginningOfWeek) &&
        Objects.equals(this.browserNotificationsDisabled, settings.browserNotificationsDisabled) &&
        Objects.equals(this.contentLanguages, settings.contentLanguages) &&
        Objects.equals(this.createdAt, settings.createdAt) &&
        Objects.equals(this.denyIframeIntegration, settings.denyIframeIntegration) &&
        Objects.equals(this.disablePasswordAutocomplete, settings.disablePasswordAutocomplete) &&
        Objects.equals(this.displayOnlyUnknownBbcode, settings.displayOnlyUnknownBbcode) &&
        Objects.equals(this.dumpInPreprod, settings.dumpInPreprod) &&
        Objects.equals(this.enableAutoScrollDown, settings.enableAutoScrollDown) &&
        Objects.equals(this.expirePasswordAfter, settings.expirePasswordAfter) &&
        Objects.equals(this.expirePasswordEnabled, settings.expirePasswordEnabled) &&
        Objects.equals(this.fteDuration, settings.fteDuration) &&
        Objects.equals(this.id, settings.id) &&
        Objects.equals(this.identityMerge, settings.identityMerge) &&
        Objects.equals(this.interventionClosingPeriod, settings.interventionClosingPeriod) &&
        Objects.equals(this.interventionDeferRates, settings.interventionDeferRates) &&
        Objects.equals(this.interventionDeferThreshold, settings.interventionDeferThreshold) &&
        Objects.equals(this.interventionRates, settings.interventionRates) &&
        Objects.equals(this.locale, settings.locale) &&
        Objects.equals(this.multiLang, settings.multiLang) &&
        Objects.equals(this.name, settings.name) &&
        Objects.equals(this.passwordArchivableEnabled, settings.passwordArchivableEnabled) &&
        Objects.equals(this.passwordArchivableSize, settings.passwordArchivableSize) &&
        Objects.equals(this.passwordMinLength, settings.passwordMinLength) &&
        Objects.equals(this.passwordNonWord, settings.passwordNonWord) &&
        Objects.equals(this.passwordNumbers, settings.passwordNumbers) &&
        Objects.equals(this.passwordRecoveryDisabled, settings.passwordRecoveryDisabled) &&
        Objects.equals(this.pushEnabled, settings.pushEnabled) &&
        Objects.equals(this.replyAsAnyIdentity, settings.replyAsAnyIdentity) &&
        Objects.equals(this.rtlSupport, settings.rtlSupport) &&
        Objects.equals(this.selfApprovalRequired, settings.selfApprovalRequired) &&
        Objects.equals(this.sessionTimeout, settings.sessionTimeout) &&
        Objects.equals(this.shardingKey, settings.shardingKey) &&
        Objects.equals(this.spellchecking, settings.spellchecking) &&
        Objects.equals(this.style, settings.style) &&
        Objects.equals(this.thirdPartyServicesDisabled, settings.thirdPartyServicesDisabled) &&
        Objects.equals(this.timezone, settings.timezone) &&
        Objects.equals(this.type, settings.type) &&
        Objects.equals(this.updatedAt, settings.updatedAt) &&
        Objects.equals(this.urgentTaskThreshold, settings.urgentTaskThreshold) &&
        Objects.equals(this.useTwoLettersAvatars, settings.useTwoLettersAvatars);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activityPresenceThreshold, activityTracking, beginningOfWeek, browserNotificationsDisabled, contentLanguages, createdAt, denyIframeIntegration, disablePasswordAutocomplete, displayOnlyUnknownBbcode, dumpInPreprod, enableAutoScrollDown, expirePasswordAfter, expirePasswordEnabled, fteDuration, id, identityMerge, interventionClosingPeriod, interventionDeferRates, interventionDeferThreshold, interventionRates, locale, multiLang, name, passwordArchivableEnabled, passwordArchivableSize, passwordMinLength, passwordNonWord, passwordNumbers, passwordRecoveryDisabled, pushEnabled, replyAsAnyIdentity, rtlSupport, selfApprovalRequired, sessionTimeout, shardingKey, spellchecking, style, thirdPartyServicesDisabled, timezone, type, updatedAt, urgentTaskThreshold, useTwoLettersAvatars);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Settings {\n");
    sb.append("    activityPresenceThreshold: ").append(toIndentedString(activityPresenceThreshold)).append("\n");
    sb.append("    activityTracking: ").append(toIndentedString(activityTracking)).append("\n");
    sb.append("    beginningOfWeek: ").append(toIndentedString(beginningOfWeek)).append("\n");
    sb.append("    browserNotificationsDisabled: ").append(toIndentedString(browserNotificationsDisabled)).append("\n");
    sb.append("    contentLanguages: ").append(toIndentedString(contentLanguages)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    denyIframeIntegration: ").append(toIndentedString(denyIframeIntegration)).append("\n");
    sb.append("    disablePasswordAutocomplete: ").append(toIndentedString(disablePasswordAutocomplete)).append("\n");
    sb.append("    displayOnlyUnknownBbcode: ").append(toIndentedString(displayOnlyUnknownBbcode)).append("\n");
    sb.append("    dumpInPreprod: ").append(toIndentedString(dumpInPreprod)).append("\n");
    sb.append("    enableAutoScrollDown: ").append(toIndentedString(enableAutoScrollDown)).append("\n");
    sb.append("    expirePasswordAfter: ").append(toIndentedString(expirePasswordAfter)).append("\n");
    sb.append("    expirePasswordEnabled: ").append(toIndentedString(expirePasswordEnabled)).append("\n");
    sb.append("    fteDuration: ").append(toIndentedString(fteDuration)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    identityMerge: ").append(toIndentedString(identityMerge)).append("\n");
    sb.append("    interventionClosingPeriod: ").append(toIndentedString(interventionClosingPeriod)).append("\n");
    sb.append("    interventionDeferRates: ").append(toIndentedString(interventionDeferRates)).append("\n");
    sb.append("    interventionDeferThreshold: ").append(toIndentedString(interventionDeferThreshold)).append("\n");
    sb.append("    interventionRates: ").append(toIndentedString(interventionRates)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    multiLang: ").append(toIndentedString(multiLang)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    passwordArchivableEnabled: ").append(toIndentedString(passwordArchivableEnabled)).append("\n");
    sb.append("    passwordArchivableSize: ").append(toIndentedString(passwordArchivableSize)).append("\n");
    sb.append("    passwordMinLength: ").append(toIndentedString(passwordMinLength)).append("\n");
    sb.append("    passwordNonWord: ").append(toIndentedString(passwordNonWord)).append("\n");
    sb.append("    passwordNumbers: ").append(toIndentedString(passwordNumbers)).append("\n");
    sb.append("    passwordRecoveryDisabled: ").append(toIndentedString(passwordRecoveryDisabled)).append("\n");
    sb.append("    pushEnabled: ").append(toIndentedString(pushEnabled)).append("\n");
    sb.append("    replyAsAnyIdentity: ").append(toIndentedString(replyAsAnyIdentity)).append("\n");
    sb.append("    rtlSupport: ").append(toIndentedString(rtlSupport)).append("\n");
    sb.append("    selfApprovalRequired: ").append(toIndentedString(selfApprovalRequired)).append("\n");
    sb.append("    sessionTimeout: ").append(toIndentedString(sessionTimeout)).append("\n");
    sb.append("    shardingKey: ").append(toIndentedString(shardingKey)).append("\n");
    sb.append("    spellchecking: ").append(toIndentedString(spellchecking)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("    thirdPartyServicesDisabled: ").append(toIndentedString(thirdPartyServicesDisabled)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    urgentTaskThreshold: ").append(toIndentedString(urgentTaskThreshold)).append("\n");
    sb.append("    useTwoLettersAvatars: ").append(toIndentedString(useTwoLettersAvatars)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

