/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.JSON;


/**
 * SourceAutoResponseTriggersInner
 */
@JsonPropertyOrder({
  SourceAutoResponseTriggersInner.JSON_PROPERTY_LANGUAGE,
  SourceAutoResponseTriggersInner.JSON_PROPERTY_CREATED_FROM_TRIGGER,
  SourceAutoResponseTriggersInner.JSON_PROPERTY_BODY
})
@JsonTypeName("Source_auto_response_triggers_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-03-13T22:37:55.741968+01:00[Europe/Paris]")
public class SourceAutoResponseTriggersInner implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_CREATED_FROM_TRIGGER = "created_from_trigger";
  private String createdFromTrigger;

  public static final String JSON_PROPERTY_BODY = "body";
  private String body;

  public SourceAutoResponseTriggersInner() { 
  }

  public SourceAutoResponseTriggersInner language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguage(String language) {
    this.language = language;
  }


  public SourceAutoResponseTriggersInner createdFromTrigger(String createdFromTrigger) {
    this.createdFromTrigger = createdFromTrigger;
    return this;
  }

   /**
   * Get createdFromTrigger
   * @return createdFromTrigger
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_FROM_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedFromTrigger() {
    return createdFromTrigger;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_FROM_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedFromTrigger(String createdFromTrigger) {
    this.createdFromTrigger = createdFromTrigger;
  }


  public SourceAutoResponseTriggersInner body(String body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BODY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBody() {
    return body;
  }


  @JsonProperty(JSON_PROPERTY_BODY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBody(String body) {
    this.body = body;
  }


  /**
   * Return true if this Source_auto_response_triggers_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceAutoResponseTriggersInner sourceAutoResponseTriggersInner = (SourceAutoResponseTriggersInner) o;
    return Objects.equals(this.language, sourceAutoResponseTriggersInner.language) &&
        Objects.equals(this.createdFromTrigger, sourceAutoResponseTriggersInner.createdFromTrigger) &&
        Objects.equals(this.body, sourceAutoResponseTriggersInner.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, createdFromTrigger, body);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceAutoResponseTriggersInner {\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    createdFromTrigger: ").append(toIndentedString(createdFromTrigger)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

