/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.SurveyQuestionReply;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.JSON;


/**
 * SurveyResponseQuestion
 */
@JsonPropertyOrder({
  SurveyResponseQuestion.JSON_PROPERTY_FOREIGN_ID,
  SurveyResponseQuestion.JSON_PROPERTY_TEXT,
  SurveyResponseQuestion.JSON_PROPERTY_REPLIES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-28T22:45:26.654875700+02:00[Europe/Paris]")
public class SurveyResponseQuestion implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_FOREIGN_ID = "foreign_id";
  private String foreignId;

  public static final String JSON_PROPERTY_TEXT = "text";
  private String text;

  public static final String JSON_PROPERTY_REPLIES = "replies";
  private List<SurveyQuestionReply> replies = null;

  public SurveyResponseQuestion() { 
  }

  public SurveyResponseQuestion foreignId(String foreignId) {
    this.foreignId = foreignId;
    return this;
  }

   /**
   * The survey provider&#39;s id for this question.
   * @return foreignId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOREIGN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getForeignId() {
    return foreignId;
  }


  @JsonProperty(JSON_PROPERTY_FOREIGN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForeignId(String foreignId) {
    this.foreignId = foreignId;
  }


  public SurveyResponseQuestion text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The question&#39;s body.
   * @return text
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(String text) {
    this.text = text;
  }


  public SurveyResponseQuestion replies(List<SurveyQuestionReply> replies) {
    this.replies = replies;
    return this;
  }

  public SurveyResponseQuestion addRepliesItem(SurveyQuestionReply repliesItem) {
    if (this.replies == null) {
      this.replies = new ArrayList<>();
    }
    this.replies.add(repliesItem);
    return this;
  }

   /**
   * The question&#39;s replies. Multiple choices questions can have more than 1 element.
   * @return replies
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SurveyQuestionReply> getReplies() {
    return replies;
  }


  @JsonProperty(JSON_PROPERTY_REPLIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplies(List<SurveyQuestionReply> replies) {
    this.replies = replies;
  }


  /**
   * Return true if this SurveyResponseQuestion object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SurveyResponseQuestion surveyResponseQuestion = (SurveyResponseQuestion) o;
    return Objects.equals(this.foreignId, surveyResponseQuestion.foreignId) &&
        Objects.equals(this.text, surveyResponseQuestion.text) &&
        Objects.equals(this.replies, surveyResponseQuestion.replies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(foreignId, text, replies);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SurveyResponseQuestion {\n");
    sb.append("    foreignId: ").append(toIndentedString(foreignId)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    replies: ").append(toIndentedString(replies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

