/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.handler.JSON;


/**
 * UserCapacityChannelsInner
 */
@JsonPropertyOrder({
  UserCapacityChannelsInner.JSON_PROPERTY_ID,
  UserCapacityChannelsInner.JSON_PROPERTY_DEFAULT_CAPACITY,
  UserCapacityChannelsInner.JSON_PROPERTY_MAX_CAPACITY
})
@JsonTypeName("UserCapacity_channels_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-03-13T22:37:55.741968+01:00[Europe/Paris]")
public class UserCapacityChannelsInner implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_DEFAULT_CAPACITY = "default_capacity";
  private Integer defaultCapacity;

  public static final String JSON_PROPERTY_MAX_CAPACITY = "max_capacity";
  private Integer maxCapacity;

  public UserCapacityChannelsInner() { 
  }

  public UserCapacityChannelsInner id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public UserCapacityChannelsInner defaultCapacity(Integer defaultCapacity) {
    this.defaultCapacity = defaultCapacity;
    return this;
  }

   /**
   * Get defaultCapacity
   * @return defaultCapacity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDefaultCapacity() {
    return defaultCapacity;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultCapacity(Integer defaultCapacity) {
    this.defaultCapacity = defaultCapacity;
  }


  public UserCapacityChannelsInner maxCapacity(Integer maxCapacity) {
    this.maxCapacity = maxCapacity;
    return this;
  }

   /**
   * Get maxCapacity
   * @return maxCapacity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxCapacity() {
    return maxCapacity;
  }


  @JsonProperty(JSON_PROPERTY_MAX_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxCapacity(Integer maxCapacity) {
    this.maxCapacity = maxCapacity;
  }


  /**
   * Return true if this UserCapacity_channels_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserCapacityChannelsInner userCapacityChannelsInner = (UserCapacityChannelsInner) o;
    return Objects.equals(this.id, userCapacityChannelsInner.id) &&
        Objects.equals(this.defaultCapacity, userCapacityChannelsInner.defaultCapacity) &&
        Objects.equals(this.maxCapacity, userCapacityChannelsInner.maxCapacity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, defaultCapacity, maxCapacity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserCapacityChannelsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    defaultCapacity: ").append(toIndentedString(defaultCapacity)).append("\n");
    sb.append("    maxCapacity: ").append(toIndentedString(maxCapacity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

