/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.AgentCustomStatus;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.AgentStatusChannel;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AgentStatus
 */
public class AgentStatusTest {
    private final AgentStatus model = new AgentStatus();

    /**
     * Model tests for AgentStatus
     */
    @Test
    public void testAgentStatus() {
        // TODO: test AgentStatus
    }

    /**
     * Test the property 'agentId'
     */
    @Test
    public void agentIdTest() {
        // TODO: test agentId
    }

    /**
     * Test the property 'channels'
     */
    @Test
    public void channelsTest() {
        // TODO: test channels
    }

    /**
     * Test the property 'customStatus'
     */
    @Test
    public void customStatusTest() {
        // TODO: test customStatus
    }

}
