/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EventExtraInfo
 */
public class EventExtraInfoTest {
    private final EventExtraInfo model = new EventExtraInfo();

    /**
     * Model tests for EventExtraInfo
     */
    @Test
    public void testEventExtraInfo() {
        // TODO: test EventExtraInfo
    }

    /**
     * Test the property 'authenticationStrategy'
     */
    @Test
    public void authenticationStrategyTest() {
        // TODO: test authenticationStrategy
    }

    /**
     * Test the property 'businessTimeSheetId'
     */
    @Test
    public void businessTimeSheetIdTest() {
        // TODO: test businessTimeSheetId
    }

    /**
     * Test the property 'categoryIds'
     */
    @Test
    public void categoryIdsTest() {
        // TODO: test categoryIds
    }

    /**
     * Test the property 'closedAutomatically'
     */
    @Test
    public void closedAutomaticallyTest() {
        // TODO: test closedAutomatically
    }

    /**
     * Test the property 'contentId'
     */
    @Test
    public void contentIdTest() {
        // TODO: test contentId
    }

    /**
     * Test the property 'contentSourceId'
     */
    @Test
    public void contentSourceIdTest() {
        // TODO: test contentSourceId
    }

    /**
     * Test the property 'contentThreadId'
     */
    @Test
    public void contentThreadIdTest() {
        // TODO: test contentThreadId
    }

    /**
     * Test the property 'deferredDuration'
     */
    @Test
    public void deferredDurationTest() {
        // TODO: test deferredDuration
    }

    /**
     * Test the property 'deletions'
     */
    @Test
    public void deletionsTest() {
        // TODO: test deletions
    }

    /**
     * Test the property 'foreignId'
     */
    @Test
    public void foreignIdTest() {
        // TODO: test foreignId
    }

    /**
     * Test the property 'interventionId'
     */
    @Test
    public void interventionIdTest() {
        // TODO: test interventionId
    }

    /**
     * Test the property 'requestIp'
     */
    @Test
    public void requestIpTest() {
        // TODO: test requestIp
    }

    /**
     * Test the property 'taskId'
     */
    @Test
    public void taskIdTest() {
        // TODO: test taskId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
