/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Intervention
 */
public class InterventionTest {
    private final Intervention model = new Intervention();

    /**
     * Model tests for Intervention
     */
    @Test
    public void testIntervention() {
        // TODO: test Intervention
    }

    /**
     * Test the property 'categoryIds'
     */
    @Test
    public void categoryIdsTest() {
        // TODO: test categoryIds
    }

    /**
     * Test the property 'closed'
     */
    @Test
    public void closedTest() {
        // TODO: test closed
    }

    /**
     * Test the property 'closedAt'
     */
    @Test
    public void closedAtTest() {
        // TODO: test closedAt
    }

    /**
     * Test the property 'commentsCount'
     */
    @Test
    public void commentsCountTest() {
        // TODO: test commentsCount
    }

    /**
     * Test the property 'contentId'
     */
    @Test
    public void contentIdTest() {
        // TODO: test contentId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'deferredAt'
     */
    @Test
    public void deferredAtTest() {
        // TODO: test deferredAt
    }

    /**
     * Test the property 'firstUserReplyId'
     */
    @Test
    public void firstUserReplyIdTest() {
        // TODO: test firstUserReplyId
    }

    /**
     * Test the property 'firstUserReplyIn'
     */
    @Test
    public void firstUserReplyInTest() {
        // TODO: test firstUserReplyIn
    }

    /**
     * Test the property 'firstUserReplyInBh'
     */
    @Test
    public void firstUserReplyInBhTest() {
        // TODO: test firstUserReplyInBh
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'identityId'
     */
    @Test
    public void identityIdTest() {
        // TODO: test identityId
    }

    /**
     * Test the property 'lastUserReplyIn'
     */
    @Test
    public void lastUserReplyInTest() {
        // TODO: test lastUserReplyIn
    }

    /**
     * Test the property 'lastUserReplyInBh'
     */
    @Test
    public void lastUserReplyInBhTest() {
        // TODO: test lastUserReplyInBh
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'threadId'
     */
    @Test
    public void threadIdTest() {
        // TODO: test threadId
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'userRepliesCount'
     */
    @Test
    public void userRepliesCountTest() {
        // TODO: test userRepliesCount
    }

    /**
     * Test the property 'userReplyInAverage'
     */
    @Test
    public void userReplyInAverageTest() {
        // TODO: test userReplyInAverage
    }

    /**
     * Test the property 'userReplyInAverageBh'
     */
    @Test
    public void userReplyInAverageBhTest() {
        // TODO: test userReplyInAverageBh
    }

    /**
     * Test the property 'userReplyInAverageCount'
     */
    @Test
    public void userReplyInAverageCountTest() {
        // TODO: test userReplyInAverageCount
    }

    /**
     * Test the property 'satisfactionGrade'
     */
    @Test
    public void satisfactionGradeTest() {
        // TODO: test satisfactionGrade
    }

    /**
     * Test the property 'satisfactionAnsweredAt'
     */
    @Test
    public void satisfactionAnsweredAtTest() {
        // TODO: test satisfactionAnsweredAt
    }

    /**
     * Test the property 'satisfactionSentAt'
     */
    @Test
    public void satisfactionSentAtTest() {
        // TODO: test satisfactionSentAt
    }

    /**
     * Test the property 'surveyResponseId'
     */
    @Test
    public void surveyResponseIdTest() {
        // TODO: test surveyResponseId
    }

    /**
     * Test the property 'surveyId'
     */
    @Test
    public void surveyIdTest() {
        // TODO: test surveyId
    }

}
