/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.SurveyResponseQuestion;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SurveyResponse
 */
public class SurveyResponseTest {
    private final SurveyResponse model = new SurveyResponse();

    /**
     * Model tests for SurveyResponse
     */
    @Test
    public void testSurveyResponse() {
        // TODO: test SurveyResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'mainIndicator'
     */
    @Test
    public void mainIndicatorTest() {
        // TODO: test mainIndicator
    }

    /**
     * Test the property 'mainIndicatorScaled'
     */
    @Test
    public void mainIndicatorScaledTest() {
        // TODO: test mainIndicatorScaled
    }

    /**
     * Test the property 'interventionId'
     */
    @Test
    public void interventionIdTest() {
        // TODO: test interventionId
    }

    /**
     * Test the property 'surveyId'
     */
    @Test
    public void surveyIdTest() {
        // TODO: test surveyId
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'responseForeignId'
     */
    @Test
    public void responseForeignIdTest() {
        // TODO: test responseForeignId
    }

    /**
     * Test the property 'questions'
     */
    @Test
    public void questionsTest() {
        // TODO: test questions
    }

}
