/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.SurveyQuestionReply;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SurveyResponseQuestion
 */
public class SurveyResponseQuestionTest {
    private final SurveyResponseQuestion model = new SurveyResponseQuestion();

    /**
     * Model tests for SurveyResponseQuestion
     */
    @Test
    public void testSurveyResponseQuestion() {
        // TODO: test SurveyResponseQuestion
    }

    /**
     * Test the property 'foreignId'
     */
    @Test
    public void foreignIdTest() {
        // TODO: test foreignId
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'replies'
     */
    @Test
    public void repliesTest() {
        // TODO: test replies
    }

}
