/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Task
 */
public class TaskTest {
    private final Task model = new Task();

    /**
     * Model tests for Task
     */
    @Test
    public void testTask() {
        // TODO: test Task
    }

    /**
     * Test the property 'acceptedAt'
     */
    @Test
    public void acceptedAtTest() {
        // TODO: test acceptedAt
    }

    /**
     * Test the property 'agentIds'
     */
    @Test
    public void agentIdsTest() {
        // TODO: test agentIds
    }

    /**
     * Test the property 'channelId'
     */
    @Test
    public void channelIdTest() {
        // TODO: test channelId
    }

    /**
     * Test the property 'completedAt'
     */
    @Test
    public void completedAtTest() {
        // TODO: test completedAt
    }

    /**
     * Test the property 'contentId'
     */
    @Test
    public void contentIdTest() {
        // TODO: test contentId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'expireAt'
     */
    @Test
    public void expireAtTest() {
        // TODO: test expireAt
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'interventionId'
     */
    @Test
    public void interventionIdTest() {
        // TODO: test interventionId
    }

    /**
     * Test the property 'lockedAt'
     */
    @Test
    public void lockedAtTest() {
        // TODO: test lockedAt
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'step'
     */
    @Test
    public void stepTest() {
        // TODO: test step
    }

    /**
     * Test the property 'threadId'
     */
    @Test
    public void threadIdTest() {
        // TODO: test threadId
    }

    /**
     * Test the property 'transferedAt'
     */
    @Test
    public void transferedAtTest() {
        // TODO: test transferedAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
