/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model.TimeSheetHoliday;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TimeSheet
 */
public class TimeSheetTest {
    private final TimeSheet model = new TimeSheet();

    /**
     * Model tests for TimeSheet
     */
    @Test
    public void testTimeSheet() {
        // TODO: test TimeSheet
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'fridayHours'
     */
    @Test
    public void fridayHoursTest() {
        // TODO: test fridayHours
    }

    /**
     * Test the property 'holidays'
     */
    @Test
    public void holidaysTest() {
        // TODO: test holidays
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'mondayHours'
     */
    @Test
    public void mondayHoursTest() {
        // TODO: test mondayHours
    }

    /**
     * Test the property 'saturdayHours'
     */
    @Test
    public void saturdayHoursTest() {
        // TODO: test saturdayHours
    }

    /**
     * Test the property 'sourceIds'
     */
    @Test
    public void sourceIdsTest() {
        // TODO: test sourceIds
    }

    /**
     * Test the property 'sundayHours'
     */
    @Test
    public void sundayHoursTest() {
        // TODO: test sundayHours
    }

    /**
     * Test the property 'thursdayHours'
     */
    @Test
    public void thursdayHoursTest() {
        // TODO: test thursdayHours
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'tuesdayHours'
     */
    @Test
    public void tuesdayHoursTest() {
        // TODO: test tuesdayHours
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'wednesdayHours'
     */
    @Test
    public void wednesdayHoursTest() {
        // TODO: test wednesdayHours
    }

}
