/*
 * RingCentral Engage Digital API
 * REST API for RingCentral Engage Digital
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.b_qiao.pers.lab.rest.ringcentral_engage_digital_client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserCapacityChannelsInner
 */
public class UserCapacityChannelsInnerTest {
    private final UserCapacityChannelsInner model = new UserCapacityChannelsInner();

    /**
     * Model tests for UserCapacityChannelsInner
     */
    @Test
    public void testUserCapacityChannelsInner() {
        // TODO: test UserCapacityChannelsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'defaultCapacity'
     */
    @Test
    public void defaultCapacityTest() {
        // TODO: test defaultCapacity
    }

    /**
     * Test the property 'maxCapacity'
     */
    @Test
    public void maxCapacityTest() {
        // TODO: test maxCapacity
    }

}
